//
//  ProgramCatalog.cpp
//  MNN
//
//  Created by MNN on 2026/08/10.
//  Copyright © 2018, Alibaba Group Holding Limited
//

#include "ProgramCatalog.hpp"

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <map>
#include <sstream>

#include <dirent.h>

// Pulls in OpenCLProgramMap: the name to source table generated by opencl_codegen.py
// and linked into libMNN. The *_mnn_cl.cpp translation units define the sources.
#include "opencl_source_map.hpp"

namespace clprof {

int ProgramSource::lines() const {
    if (source.empty()) {
        return 0;
    }
    int count = 1;
    for (char character : source) {
        if ('\n' == character) {
            ++count;
        }
    }
    return count;
}

namespace catalog {

std::vector<ProgramSource> embedded() {
    std::vector<ProgramSource> programs;
    programs.reserve(MNN::OpenCLProgramMap.size());
    for (const auto& entry : MNN::OpenCLProgramMap) {
        if (nullptr == entry.second) {
            continue;
        }
        ProgramSource program;
        program.name   = entry.first;
        program.origin = "embedded";
        program.source = entry.second;
        programs.push_back(program);
    }
    return programs;
}

bool fromFile(const std::string& path, ProgramSource& out, std::string& error) {
    std::ifstream file(path.c_str(), std::ios::binary);
    if (!file.is_open()) {
        error = "cannot open " + path;
        return false;
    }
    std::ostringstream content;
    content << file.rdbuf();

    std::string stem       = path;
    const size_t slash     = stem.find_last_of('/');
    if (std::string::npos != slash) {
        stem = stem.substr(slash + 1);
    }
    const size_t dot = stem.find_last_of('.');
    if (std::string::npos != dot) {
        stem = stem.substr(0, dot);
    }

    out.name   = stem;
    out.origin = path;
    out.source = content.str();
    if (out.source.empty()) {
        error = path + " is empty";
        return false;
    }
    return true;
}

bool fromDirectory(const std::string& directory, std::vector<ProgramSource>& out, std::string& error) {
    DIR* handle = opendir(directory.c_str());
    if (nullptr == handle) {
        error = "cannot open directory " + directory;
        return false;
    }

    std::vector<std::string> files;
    while (const dirent* entry = readdir(handle)) {
        const std::string name = entry->d_name;
        if (name.size() < 4 || name.compare(name.size() - 3, 3, ".cl") != 0) {
            continue;
        }
        files.push_back(directory + "/" + name);
    }
    closedir(handle);
    std::sort(files.begin(), files.end());

    for (const std::string& file : files) {
        ProgramSource program;
        std::string readError;
        if (!fromFile(file, program, readError)) {
            error = readError;
            return false;
        }
        out.push_back(program);
    }
    if (out.empty()) {
        error = "no *.cl file found in " + directory;
        return false;
    }
    return true;
}

std::vector<ProgramSource> filter(const std::vector<ProgramSource>& programs,
                                  const std::vector<std::string>& patterns) {
    if (patterns.empty()) {
        return programs;
    }
    std::vector<ProgramSource> selected;
    for (const ProgramSource& program : programs) {
        for (const std::string& pattern : patterns) {
            if (globMatch(pattern, program.name)) {
                selected.push_back(program);
                break;
            }
        }
    }
    return selected;
}

}  // namespace catalog

bool globMatch(const std::string& pattern, const std::string& text) {
    size_t patternIndex     = 0;
    size_t textIndex        = 0;
    size_t starIndex        = std::string::npos;
    size_t textAfterStar    = 0;

    while (textIndex < text.size()) {
        if (patternIndex < pattern.size() &&
            ('?' == pattern[patternIndex] || pattern[patternIndex] == text[textIndex])) {
            ++patternIndex;
            ++textIndex;
        } else if (patternIndex < pattern.size() && '*' == pattern[patternIndex]) {
            starIndex     = patternIndex++;
            textAfterStar = textIndex;
        } else if (std::string::npos != starIndex) {
            patternIndex = starIndex + 1;
            textIndex    = ++textAfterStar;
        } else {
            return false;
        }
    }
    while (patternIndex < pattern.size() && '*' == pattern[patternIndex]) {
        ++patternIndex;
    }
    return patternIndex == pattern.size();
}

std::string mnnBuildOptions(int precisionLevel) {
    std::string options;
    if (2 == precisionLevel) {  // fp16 storage, fp16 math
        options =
            "-DFLOAT=half -DFLOAT2=half2 -DFLOAT3=half3 -DFLOAT4=half4 -DFLOAT8=half8 -DFLOAT16=half16 "
            "-DCOMPUTE_FLOAT=half -DCOMPUTE_FLOAT2=half2 -DCOMPUTE_FLOAT3=half3 -DCOMPUTE_FLOAT4=half4 "
            "-DCOMPUTE_FLOAT8=half8 -DCOMPUTE_FLOAT16=half16 -DCONVERT_COMPUTE_FLOAT=convert_half "
            "-DCONVERT_COMPUTE_FLOAT2=convert_half2 -DCONVERT_COMPUTE_FLOAT3=convert_half3 "
            "-DCONVERT_COMPUTE_FLOAT4=convert_half4 -DCONVERT_COMPUTE_FLOAT8=convert_half8 "
            "-DCONVERT_COMPUTE_FLOAT16=convert_half16 -DRI_F=read_imageh -DWI_F=write_imageh "
            "-DCONVERT_FLOAT=convert_half -DCONVERT_FLOAT2=convert_half2 -DCONVERT_FLOAT3=convert_half3 "
            "-DCONVERT_FLOAT4=convert_half4 -DCONVERT_FLOAT8=convert_half8 -DCONVERT_FLOAT16=convert_half16 "
            "-DMNN_SUPPORT_FP16";
    } else if (0 == precisionLevel) {  // fp16 storage, fp32 math
        options =
            "-DFLOAT=half -DFLOAT2=half2 -DFLOAT3=half3 -DFLOAT4=half4 -DFLOAT8=half8 -DFLOAT16=half16 "
            "-DCOMPUTE_FLOAT=float -DCOMPUTE_FLOAT2=float2 -DCOMPUTE_FLOAT3=float3 -DCOMPUTE_FLOAT4=float4 "
            "-DCOMPUTE_FLOAT8=float8 -DCOMPUTE_FLOAT16=float16 -DCONVERT_COMPUTE_FLOAT=convert_float "
            "-DCONVERT_COMPUTE_FLOAT2=convert_float2 -DCONVERT_COMPUTE_FLOAT3=convert_float3 "
            "-DCONVERT_COMPUTE_FLOAT4=convert_float4 -DCONVERT_COMPUTE_FLOAT8=convert_float8 "
            "-DCONVERT_COMPUTE_FLOAT16=convert_float16 -DCONVERT_FLOAT=convert_half "
            "-DCONVERT_FLOAT2=convert_half2 -DCONVERT_FLOAT3=convert_half3 -DCONVERT_FLOAT4=convert_half4 "
            "-DCONVERT_FLOAT8=convert_half8 -DCONVERT_FLOAT16=convert_half16 -DRI_F=read_imageh "
            "-DWI_F=write_imageh -DMNN_SUPPORT_FP16";
    } else {  // fp32 storage, fp32 math
        options =
            "-DFLOAT=float -DFLOAT2=float2 -DFLOAT3=float3 -DFLOAT4=float4 -DFLOAT8=float8 -DFLOAT16=float16 "
            "-DCOMPUTE_FLOAT=float -DCOMPUTE_FLOAT2=float2 -DCOMPUTE_FLOAT3=float3 -DCOMPUTE_FLOAT4=float4 "
            "-DCOMPUTE_FLOAT8=float8 -DCOMPUTE_FLOAT16=float16 -DCONVERT_COMPUTE_FLOAT=convert_float "
            "-DCONVERT_COMPUTE_FLOAT2=convert_float2 -DCONVERT_COMPUTE_FLOAT3=convert_float3 "
            "-DCONVERT_COMPUTE_FLOAT4=convert_float4 -DCONVERT_COMPUTE_FLOAT8=convert_float8 "
            "-DCONVERT_COMPUTE_FLOAT16=convert_float16 -DRI_F=read_imagef -DWI_F=write_imagef "
            "-DCONVERT_FLOAT=convert_float -DCONVERT_FLOAT2=convert_float2 -DCONVERT_FLOAT3=convert_float3 "
            "-DCONVERT_FLOAT4=convert_float4 -DCONVERT_FLOAT8=convert_float8 -DCONVERT_FLOAT16=convert_float16";
    }

    // OpenCLRuntime only emits the tensor type defines when an Execution passes its
    // input and output tensors. They are added here for the float case because a
    // large part of the kernel set does not preprocess without them.
    if (1 != precisionLevel) {
        options +=
            " -DINPUT_TYPE_I=half -DINPUT_TYPE_I4=half4 -DINPUT_TYPE=half -DINPUT_TYPE4=half4"
            " -DINPUT_TYPE16=half16 -DRI_DATA=read_imageh"
            " -DOUTPUT_TYPE_I=half -DOUTPUT_TYPE_I4=half4 -DCONVERT_OUTPUT_I4=convert_half4"
            " -DOUTPUT_TYPE=half -DOUTPUT_TYPE4=half4 -DOUTPUT_TYPE16=half16"
            " -DCONVERT_OUTPUT4=convert_half4 -DCONVERT_OUTPUT16=convert_half16 -DWI_DATA=write_imageh";
    } else {
        options +=
            " -DINPUT_TYPE_I=float -DINPUT_TYPE_I4=float4 -DINPUT_TYPE=float -DINPUT_TYPE4=float4"
            " -DINPUT_TYPE16=float16 -DRI_DATA=read_imagef"
            " -DOUTPUT_TYPE_I=float -DOUTPUT_TYPE_I4=float4 -DCONVERT_OUTPUT_I4=convert_float4"
            " -DOUTPUT_TYPE=float -DOUTPUT_TYPE4=float4 -DOUTPUT_TYPE16=float16"
            " -DCONVERT_OUTPUT4=convert_float4 -DCONVERT_OUTPUT16=convert_float16 -DWI_DATA=write_imagef";
    }

    options += " -DSET_ATTRIBUTE=false";
    options += " -cl-mad-enable -w";
    return options;
}

std::string programDefines(const std::string& programName) {
    // The values mirror what the corresponding Execution passes at runtime, so the
    // compiler sees the same code MNN makes it compile. Where an Execution picks a
    // value per tensor shape, the most common one is used and named here.
    static const std::map<std::string, const char*> kDefines = {
        {"binary", "-DOPERATOR=in0+in1"},               // BinaryExecution, add
        {"binary_buf", "-DOPERATOR=in0+in1"},           // BinaryBufExecution, add
        {"strassen_binary_buf", "-DOPERATOR=in0+in1 -DVEC_H=1"},  // StrassenMatmulOpenCLComputor
        {"unary", "-DOPERATOR=in*in"},                  // UnaryExecution, square
        {"unary_buf", "-DOPERATOR=in*in"},              // UnaryBufExecution, square
        {"reduction", "-DOPERATE(a,b)=(a+b) -DVALUE=0 -DLOCAL_SIZE=512"},      // ReductionExecution, sum
        {"reduction_buf", "-DOPERATE(a,b)=(a+b) -DVALUE=0 -DLOCAL_SIZE=512"},  // ReductionBufExecution, sum
        {"layernorm", "-DLOCAL_SIZE=512"},                                     // LayerNormExecution
        {"layernorm_buf", "-DLOCAL_SIZE=512"},                                 // LayerNormBufExecution
        {"groupnorm_buf", "-DLOCAL_SIZE=512"},                                 // GroupNormBufExecution
        {"glmem_convert", "-DSHARED_TO_CL -DCL_TO_SHARED"},                    // both directions
        {"linear_attention_buf", "-DLOCAL_SIZE=16 -DK_SIZE=128"},              // LinearAttentionBufExecution
        {"matmul_local_buf", "-DOPWM=64 -DOPWN=128 -DCPWK=8 -DOPTM=4 -DOPTN=8"},  // MatmulBufExecution tile path
    };

    const auto iterator = kDefines.find(programName);
    if (iterator == kDefines.end()) {
        return std::string();
    }
    return iterator->second;
}

std::string saltedSource(const std::string& source, unsigned int salt) {
    // A define alone is not enough: some drivers hash the preprocessed source, and an
    // unused macro leaves that hash unchanged. Emitting a uniquely named constant
    // guarantees different input to the compiler and therefore a cache miss. It is
    // appended rather than prepended so it cannot come before a #pragma OPENCL
    // EXTENSION line that the kernel opens with.
    char epilogue[128];
    snprintf(epilogue, sizeof(epilogue), "\n__constant int mnn_cl_profiler_salt_%u = %u;\n", salt, salt);
    return source + epilogue;
}

}  // namespace clprof
