#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* applylut_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// ApplyLUT: per-element 1-D LUT remap with linear interpolation. A memory-bound\n"
"// element-wise op over a dense single-plane float buffer (input 0),remapped\n"
"// through a small runtime LUT (input 1,length N in [8,256]) into an identically\n"
"// shaped output. Optimized for bandwidth:\n"
"//*dense flat NCHW buffer (no NC4HW4 channel padding) set up host-side,\n"
"//*each work-item streams VEC contiguous elements with one vectorized\n"
"// load+one vectorized store (coalesced),and\n"
"//*the LUT is staged once per workgroup into local memory,so every (data-\n"
"// dependent) gather is on-chip and broadcasts for neighbouring pixels.\n"
"// Interp math runs in COMPUTE_FLOAT (fp32 even in fp16-buffer mode) to match the\n"
"// CPU reference; only the streamed pixels are stored back at FLOAT precision.\n"
"//\n"
"// Clamp-index-only semantics:\n"
"// pos=x*(N-1)\n"
"// i0=clamp((int)floor(pos),0,N-1); i1=min(i0+1,N-1)\n"
"// frac=pos-(COMPUTE_FLOAT)i0\n"
"// out=lut[i0]+frac*(lut[i1]-lut[i0])\n"
"// In-range x in [0,1] is standard lerp; out-of-range x keeps the clamped\n"
"// endpoint's slope (frac may fall outside [0,1)).\n"
"#ifndef VEC\n"
"#define VEC 4\n"
"#endif\n"
"#ifndef MAX_LUT\n"
"#define MAX_LUT 256\n"
"#endif\n"
"#define PASTE_(a,b) a##b\n"
"#define PASTE(a,b) PASTE_(a,b)\n"
"#define FLOATN PASTE(FLOAT,VEC)\n"
"#define VLOADN PASTE(vload,VEC)\n"
"#define VSTOREN PASTE(vstore,VEC)\n"
"// LUT storage: by default staged into local memory once per workgroup; with\n"
"// -DLUT_GLOBAL the tiny table is read straight from (cached) global memory,\n"
"// dropping the local buffer and the barrier. Selected host-side per device.\n"
"#ifdef LUT_GLOBAL\n"
"#define LUT_PTR __global const FLOAT*\n"
"#define LUT_READ(p,i) ((COMPUTE_FLOAT)(p)[i])\n"
"#else\n"
"#define LUT_PTR __local const COMPUTE_FLOAT*\n"
"#define LUT_READ(p,i) ((p)[i])\n"
"#endif\n"
"// One vector lane,kept in registers (swizzle access -- no addressable scratch,\n"
"// which a pointer-cast into the vector would otherwise force and spill).\n"
"#define LANE(v,s) (FLOAT)applylut_one((COMPUTE_FLOAT)(v).s,llut,maxIdx,scaleF)\n"
"// One scalar pixel: normalized value -> interpolated LUT output.\n"
"inline COMPUTE_FLOAT applylut_one(COMPUTE_FLOAT x,LUT_PTR llut,\n"
" const int maxIdx,const COMPUTE_FLOAT scaleF) {\n"
" const COMPUTE_FLOAT pos=x*scaleF;\n"
" int i0=(int)floor(pos);\n"
" i0=clamp(i0,0,maxIdx);\n"
" const int i1=min(i0+1,maxIdx);\n"
" const COMPUTE_FLOAT frac=pos-(COMPUTE_FLOAT)i0;\n"
" const COMPUTE_FLOAT lo=LUT_READ(llut,i0);\n"
" const COMPUTE_FLOAT hi=LUT_READ(llut,i1);\n"
" return mad(frac,hi-lo,lo);\n"
"}\n"
"__kernel void applylut_buf(\n"
" __global const FLOAT* input,\n"
" __global const FLOAT* lut,\n"
" __global FLOAT* output,\n"
" __private const int n,\n"
" __private const int lutSize) {\n"
"#ifdef LUT_GLOBAL\n"
" // Read the small table straight from cached global memory (no barrier).\n"
" LUT_PTR llut=lut;\n"
"#else\n"
" // Cooperative LUT stage into local memory (every work-item participates\n"
" // before the barrier -- no early return above it).\n"
" __local COMPUTE_FLOAT llut[MAX_LUT];\n"
" const int lid=get_local_id(0);\n"
" const int lsize=get_local_size(0);\n"
" for (int i=lid; i<lutSize; i += lsize) {\n"
" llut[i]=(COMPUTE_FLOAT)lut[i];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
"#endif\n"
" const int gid=get_global_id(0);\n"
" const int base=gid*VEC;\n"
" if (base >= n) {\n"
" return;\n"
" }\n"
" const int maxIdx=lutSize-1;\n"
" const COMPUTE_FLOAT scaleF=(COMPUTE_FLOAT)maxIdx;\n"
" if (base+VEC <= n) {\n"
" // Fast path: full vector,coalesced load/store. vin/vout stay in\n"
" // registers; each lane is remapped via swizzle access.\n"
" FLOATN vin=VLOADN(gid,input);\n"
" FLOATN vout;\n"
"#if VEC == 2\n"
" vout=(FLOATN)(LANE(vin,s0),LANE(vin,s1));\n"
"#elif VEC == 4\n"
" vout=(FLOATN)(LANE(vin,s0),LANE(vin,s1),LANE(vin,s2),LANE(vin,s3));\n"
"#elif VEC == 8\n"
" vout=(FLOATN)(LANE(vin,s0),LANE(vin,s1),LANE(vin,s2),LANE(vin,s3),\n"
" LANE(vin,s4),LANE(vin,s5),LANE(vin,s6),LANE(vin,s7));\n"
"#elif VEC == 16\n"
" vout=(FLOATN)(LANE(vin,s0),LANE(vin,s1),LANE(vin,s2),LANE(vin,s3),\n"
" LANE(vin,s4),LANE(vin,s5),LANE(vin,s6),LANE(vin,s7),\n"
" LANE(vin,s8),LANE(vin,s9),LANE(vin,sa),LANE(vin,sb),\n"
" LANE(vin,sc),LANE(vin,sd),LANE(vin,se),LANE(vin,sf));\n"
"#endif\n"
" VSTOREN(vout,gid,output);\n"
" } else {\n"
" // Scalar tail: dynamic sizes not divisible by VEC.\n"
" for (int c=0; base+c<n; ++c) {\n"
" output[base+c]=(FLOAT)applylut_one((COMPUTE_FLOAT)input[base+c],llut,maxIdx,scaleF);\n"
" }\n"
" }\n"
"}\n"
;
#endif
}
