#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* bincount_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// BinCount: count occurrences of each integer value of a flattened int32 input\n"
"// into a fixed number of bins (BIN_NUM). Values outside [0,BIN_NUM) are\n"
"// dropped. Output is int32 of length BIN_NUM.\n"
"//\n"
"// The fast path keeps a per-work-item private histogram in registers. A\n"
"// data-dependent array index (priv[input[i]]++) would spill that array out of\n"
"// registers into (slow) private memory,so instead each element is compared\n"
"// against every bin and the matching counter conditionally incremented\n"
"// (priv[b] += (v == b)). With BIN_NUM a small compile-time constant and the\n"
"// loop unrolled,all counters stay in registers with zero atomic contention --\n"
"// the same register-resident,contention-free structure that makes the\n"
"// Quantile count kernel fast. Cross-work-item merge is a log-tree reduction in\n"
"// local memory plus a single global atomic per bin per workgroup,so the total\n"
"// number of global atomics is only workGroups*BIN_NUM (vs. one per input\n"
"// element in the naive baseline below).\n"
"#define LOCAL_SIZE 256\n"
"#ifndef BIN_NUM\n"
"#define BIN_NUM 16\n"
"#endif\n"
"// Input element type. Integer inputs are read as int32 directly. Float inputs\n"
"// are read through the precision-dependent FLOAT macro (half in fp16 buffer\n"
"// mode,float in high precision) -- so a logically-float input whose device\n"
"// buffer is stored as half is supported -- and truncated to an int bin index\n"
"// (matching the CPU reference's static_cast<int>). Out-of-[0,BIN_NUM) indices\n"
"// match no bin in the compare below and are naturally dropped.\n"
"#ifdef BINCOUNT_IN_FLOAT\n"
"#define IN_T FLOAT\n"
"#define IN_T4 FLOAT4\n"
"#define TO_BIN(x) ((int)(x))\n"
"#else\n"
"#define IN_T int\n"
"#define IN_T4 int4\n"
"#define TO_BIN(x) (x)\n"
"#endif\n"
"// Optional binary mask (second input): elements with mask != 0 are counted,\n"
"// others dropped,output stays int32 counts. Mask may be int32 or float\n"
"// (fp16 buffer); a component's contribution is gated by (m != 0).\n"
"#ifdef BINCOUNT_MASK\n"
"#ifdef BINCOUNT_MASK_FLOAT\n"
"#define MASK_T FLOAT\n"
"#define MASK_T4 FLOAT4\n"
"#else\n"
"#define MASK_T int\n"
"#define MASK_T4 int4\n"
"#endif\n"
"#endif\n"
"__kernel void bincount_init_buf(\n"
" __global int *output,\n"
" __private const int binNum) {\n"
" const int b=get_global_id(0);\n"
" if (b >= binNum) {\n"
" return;\n"
" }\n"
" output[b]=0;\n"
"}\n"
"__kernel void bincount_count_buf(\n"
" __global const IN_T *input,\n"
"#ifdef BINCOUNT_MASK\n"
" __global const MASK_T *mask,\n"
"#endif\n"
" __global int *output,\n"
" __private const int n,\n"
" __private const int binNum) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" int priv[BIN_NUM];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b]=0;\n"
" }\n"
" // Vectorized loads: one 128-bit (int4)/64-bit (half4) transaction per 4\n"
" // elements improves memory throughput. Scalar-component comparisons each\n"
" // return 0/1 in OpenCL C,so summing them gives this group's contribution\n"
" // to bin b. With a mask,each component is additionally gated by (m != 0).\n"
" const int n4=n >> 2;\n"
" for (int i=gid; i<n4; i += gsize) {\n"
" IN_T4 v=vload4(i,input);\n"
" int vx=TO_BIN(v.x),vy=TO_BIN(v.y),vz=TO_BIN(v.z),vw=TO_BIN(v.w);\n"
"#ifdef BINCOUNT_MASK\n"
" MASK_T4 m=vload4(i,mask);\n"
" int mx=(m.x != 0),my=(m.y != 0),mz=(m.z != 0),mw=(m.w != 0);\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b] += (vx == b)*mx+(vy == b)*my+(vz == b)*mz+(vw == b)*mw;\n"
" }\n"
"#else\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b] += (vx == b)+(vy == b)+(vz == b)+(vw == b);\n"
" }\n"
"#endif\n"
" }\n"
" // Tail: the up-to-3 trailing elements when n is not a multiple of 4.\n"
" for (int i=(n4 << 2)+gid; i<n; i += gsize) {\n"
" int v=TO_BIN(input[i]);\n"
"#ifdef BINCOUNT_MASK\n"
" int keep=(mask[i] != 0);\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b] += ((v == b) ? 1 : 0)*keep;\n"
" }\n"
"#else\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b] += (v == b) ? 1 : 0;\n"
" }\n"
"#endif\n"
" }\n"
" // ---- cross-work-item merge ----\n"
"#if (BIN_NUM*LOCAL_SIZE) <= 4096\n"
" // Fused reduction: collapse all BIN_NUM bins in a single log-tree (8 barrier\n"
" // rounds for LOCAL_SIZE=256) instead of one tree per bin (~BIN_NUM*8\n"
" // barriers). This attacks the dominant cost: with each work-item doing only\n"
" // a few elements of accumulation,the per-workgroup reduction barriers were\n"
" // the bottleneck,not loads or ALU. Bin-major layout [b*LOCAL_SIZE+lid]\n"
" // keeps every reduction step's accesses contiguous across threads\n"
" // (coalesced,bank-conflict-free).\n"
" __local int reduceBuf[BIN_NUM*LOCAL_SIZE];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" reduceBuf[b*LOCAL_SIZE+lid]=priv[b];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int off=LOCAL_SIZE >> 1; off>0; off >>= 1) {\n"
" if (lid<off) {\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" reduceBuf[b*LOCAL_SIZE+lid] += reduceBuf[b*LOCAL_SIZE+lid+off];\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" atomic_add(&output[b],reduceBuf[b*LOCAL_SIZE]);\n"
" }\n"
" }\n"
"#else\n"
" // Fallback for large BIN_NUM (fused buffer would exceed local memory):\n"
" // sequential per-bin reduction over a single LOCAL_SIZE scratch buffer.\n"
" __local int reduceBuf[LOCAL_SIZE];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" reduceBuf[lid]=priv[b];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int off=LOCAL_SIZE >> 1; off>0; off >>= 1) {\n"
" if (lid<off) {\n"
" reduceBuf[lid] += reduceBuf[lid+off];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" atomic_add(&output[b],reduceBuf[0]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
"#endif\n"
"}\n"
"// Downsampled variant: counts only input[...,::stride,::stride] over the last\n"
"// two dims (nSampled ~= N/stride^2 elements),an approximate histogram that is\n"
"// far cheaper at large stride. Each work-item maps a linear sampled index k to\n"
"// a full-tensor flat offset via the sampled-grid geometry (Ws sampled columns\n"
"// per row,HsWs sampled elements per HW plane) and gathers that element. Reads\n"
"// are strided (not vectorizable/coalesced),but at stride^2-fewer elements the\n"
"// gather cost is small. Merge is identical to bincount_count_buf.\n"
"__kernel void bincount_sample_buf(\n"
" __global const IN_T *input,\n"
"#ifdef BINCOUNT_MASK\n"
" __global const MASK_T *mask,\n"
"#endif\n"
" __global int *output,\n"
" __private const int nSampled,\n"
" __private const int stride,\n"
" __private const int W,\n"
" __private const int Ws,\n"
" __private const int HsWs,\n"
" __private const int HW,\n"
" __private const int binNum) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" int priv[BIN_NUM];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b]=0;\n"
" }\n"
" for (int k=gid; k<nSampled; k += gsize) {\n"
" const int plane=k/HsWs;\n"
" const int r=k-plane*HsWs;\n"
" const int ph=r/Ws;\n"
" const int pw=r-ph*Ws;\n"
" const int flat=plane*HW+(ph*stride)*W+pw*stride;\n"
" int v=TO_BIN(input[flat]);\n"
"#ifdef BINCOUNT_MASK\n"
" int keep=(mask[flat] != 0);\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b] += ((v == b) ? 1 : 0)*keep;\n"
" }\n"
"#else\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" priv[b] += (v == b) ? 1 : 0;\n"
" }\n"
"#endif\n"
" }\n"
" // ---- cross-work-item merge (identical to bincount_count_buf) ----\n"
"#if (BIN_NUM*LOCAL_SIZE) <= 4096\n"
" __local int reduceBuf[BIN_NUM*LOCAL_SIZE];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" reduceBuf[b*LOCAL_SIZE+lid]=priv[b];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int off=LOCAL_SIZE >> 1; off>0; off >>= 1) {\n"
" if (lid<off) {\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" reduceBuf[b*LOCAL_SIZE+lid] += reduceBuf[b*LOCAL_SIZE+lid+off];\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" atomic_add(&output[b],reduceBuf[b*LOCAL_SIZE]);\n"
" }\n"
" }\n"
"#else\n"
" __local int reduceBuf[LOCAL_SIZE];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" reduceBuf[lid]=priv[b];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int off=LOCAL_SIZE >> 1; off>0; off >>= 1) {\n"
" if (lid<off) {\n"
" reduceBuf[lid] += reduceBuf[lid+off];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" atomic_add(&output[b],reduceBuf[0]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
"#endif\n"
"}\n"
"// Local-memory histogram for large BIN_NUM. The register-histogram path keeps\n"
"// priv[BIN_NUM] per work-item,which spills out of registers (and forces a\n"
"// BIN_NUM-way tree reduction) once BIN_NUM is large -- catastrophic at 256.\n"
"// Here each workgroup instead keeps a single BIN_NUM-sized histogram in local\n"
"// memory (256 ints=1KB,easily on-chip),work-items atomic-add into it,then\n"
"// cooperatively merge it to the global output (BIN_NUM global atomics per\n"
"// workgroup). Uses the sampled-grid geometry so one kernel serves both the\n"
"// contiguous (stride==1,flat==k) and downsampled (stride>1) cases.\n"
"__kernel void bincount_local_buf(\n"
" __global const IN_T *input,\n"
"#ifdef BINCOUNT_MASK\n"
" __global const MASK_T *mask,\n"
"#endif\n"
" __global int *output,\n"
" __private const int nSampled,\n"
" __private const int stride,\n"
" __private const int W,\n"
" __private const int Ws,\n"
" __private const int HsWs,\n"
" __private const int HW,\n"
" __private const int binNum) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" const int lsize=get_local_size(0);\n"
" __local int localHist[BIN_NUM];\n"
" for (int b=lid; b<BIN_NUM; b += lsize) {\n"
" localHist[b]=0;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int k=gid; k<nSampled; k += gsize) {\n"
" int flat;\n"
" if (stride <= 1) {\n"
" flat=k;\n"
" } else {\n"
" const int plane=k/HsWs;\n"
" const int r=k-plane*HsWs;\n"
" const int ph=r/Ws;\n"
" const int pw=r-ph*Ws;\n"
" flat=plane*HW+(ph*stride)*W+pw*stride;\n"
" }\n"
" int v=TO_BIN(input[flat]);\n"
" if (v >= 0 && v<binNum) {\n"
"#ifdef BINCOUNT_MASK\n"
" if (mask[flat] != 0) {\n"
" atomic_add(&localHist[v],1);\n"
" }\n"
"#else\n"
" atomic_add(&localHist[v],1);\n"
"#endif\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int b=lid; b<BIN_NUM; b += lsize) {\n"
" int c=localHist[b];\n"
" if (c != 0) {\n"
" atomic_add(&output[b],c);\n"
" }\n"
" }\n"
"}\n"
"// Naive baseline kept for on-device benchmarking only: one global atomic per\n"
"// input element straight into the BIN_NUM-sized output. Suffers heavy\n"
"// contention when BIN_NUM is small (few addresses hammered by many threads).\n"
"__kernel void bincount_naive_buf(\n"
" __global const IN_T *input,\n"
" __global int *output,\n"
" __private const int n,\n"
" __private const int binNum) {\n"
" const int gid=get_global_id(0);\n"
" if (gid >= n) {\n"
" return;\n"
" }\n"
" int v=TO_BIN(input[gid]);\n"
" if (v >= 0 && v<binNum) {\n"
" atomic_add(&output[v],1);\n"
" }\n"
"}\n"
;
#endif
}
