#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* conv_2d_hc_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_2_DIMS __private const int global_size_dim0,__private const int global_size_dim1,\n"
"#define DEAL_NON_UNIFORM_DIM2(input1, input2) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "" return; "" }\n"
"// =============================================================================================\n"
"// Shape-specialised copies of MNN's stock conv kernels,in their OWN program so conv_2d_buf.cl\n"
"// is never touched. Every shape value (HCINH/HCOUTW/HCICB/HCSH/...) arrives as a -D build\n"
"// option: the runtime expression by default,a literal under MNN_CONV_HARD=1. With literals the\n"
"// compiler folds all index arithmetic,bounds the channel/filter loops and drops halo branches.\n"
"// Deliberate duplication -- the originals stay byte-identical.\n"
"// =============================================================================================\n"
"__kernel\n"
"void conv_2d_c4h1w1_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx=out_c_w_idx/HCOUTW+out_c_base_index;\n"
" if(out_c_idx >= HCOCB) return;\n"
" const int out_w_idx=out_c_w_idx % HCOUTW;\n"
" const int out_b_idx=out_b_h_idx/HCOUTH;//equal to in_b_idx\n"
" const int out_h_idx=out_b_h_idx % HCOUTH;\n"
" \n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,bias));\n"
" \n"
" const int in_w_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_h_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" \n"
" const int kw_start=select(0,(-in_w_idx_base+HCDW-1)/HCDW,in_w_idx_base<0);\n"
" const int kh_start=select(0,(-in_h_idx_base+HCDH-1)/HCDH,in_h_idx_base<0);\n"
" const int in_w_idx_start=mad24(kw_start,HCDW,in_w_idx_base);\n"
" const int in_w_idx_end=min(mad24(HCFW,HCDW,in_w_idx_base),HCINW);\n"
" \n"
" const int in_h_idx_start=mad24(kh_start,HCDH,in_h_idx_base);\n"
" const int in_h_idx_end=min(mad24(HCFH,HCDH,in_h_idx_base),HCINH);\n"
" \n"
" const int weight_oc_offset=HCOCB*HCFH*HCFW*4;\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [1,4*icC4,ocC4*kh*kw,1] xic4\n"
" //index: [0,4*in_c_idx,out_c_idx*kh*kw+kh_start*kw+kw_start,0]\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx) *HCFH+kh_start)*HCFW+kw_start)*4;\n"
" for(int iy=in_h_idx_start; iy<in_h_idx_end; iy += HCDH) {\n"
" for(int ix=in_w_idx_start; ix<in_w_idx_end; ix += HCDW) {\n"
" int inp_offset=(((out_b_idx+in_c_idx*HCBATCH)*HCINH+iy)*HCINW+ix)*4;\n"
" COMPUTE_FLOAT4 in0=CONVERT_COMPUTE_FLOAT4(vload4(0,input+inp_offset));\n"
" \n"
" const int filter_w_inc=(ix-in_w_idx_start)/HCDW;\n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(filter_w_inc,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(filter_w_inc,weight+weight_offset+weight_oc_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(filter_w_inc,weight+weight_offset+weight_oc_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(filter_w_inc,weight+weight_offset+weight_oc_offset*3));\n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" }\n"
" weight_offset += 4*HCFW;\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,slope_ptr));\n"
" out0=select(out0*slope_in,out0,out0 >= 0);\n"
"#endif\n"
" const int out_offset=(((out_b_idx+out_c_idx*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" \n"
"}\n"
"__kernel\n"
"void conv_2d_c4h1w2_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,//generate width's num\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx=out_c_w_idx/HCWB+out_c_base_index;\n"
" if(out_c_idx >= HCOCB) return;\n"
" const int out_w_idx=(out_c_w_idx % HCWB) << 1;\n"
" const int out_b_idx=out_b_h_idx/HCOUTH;//equal to in_b_idx\n"
" const int out_h_idx=out_b_h_idx % HCOUTH;\n"
" \n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,bias));\n"
" COMPUTE_FLOAT4 out1=out0;\n"
" \n"
" const int in_w0_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_w1_idx_base=in_w0_idx_base+HCSW;\n"
" const int in_h_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" \n"
" const int kh_start=select(0,(-in_h_idx_base+HCDH-1)/HCDH,in_h_idx_base<0);\n"
" const int in_h_idx_start=mad24(kh_start,HCDH,in_h_idx_base);\n"
" const int in_h_idx_end=min(mad24(HCFH,HCDH,in_h_idx_base),HCINH);\n"
" \n"
" const int weight_oc_offset=HCOCB*HCFH*HCFW*4;\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [1,4*icC4,ocC4*kh*kw,1] xic4\n"
" //index: [0,4*in_c_idx,out_c_idx*kh*kw+kh_start*kw+kw_start,0]\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx) *HCFH+kh_start)*HCFW+0)*4;\n"
" for(int iy=in_h_idx_start; iy<in_h_idx_end; iy += HCDH) {\n"
" const int inp_offset_base=(((out_b_idx+in_c_idx*HCBATCH)*HCINH+iy)*HCINW+0)*4;\n"
" for(int fw=0; fw<HCFW; fw++) {\n"
" const int in_w0_idx=fw*HCDW+in_w0_idx_base;\n"
" const int in_w1_idx=fw*HCDW+in_w1_idx_base;\n"
" COMPUTE_FLOAT4 in0=(in_w0_idx<0 || in_w0_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w0_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in1=(in_w1_idx<0 || in_w1_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w1_idx,input+inp_offset_base));\n"
" \n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset*3));\n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" \n"
" out1=mad(in1.x,weight0,out1);\n"
" out1=mad(in1.y,weight1,out1);\n"
" out1=mad(in1.z,weight2,out1);\n"
" out1=mad(in1.w,weight3,out1);\n"
" \n"
" weight_offset += 4;\n"
" }\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
" out1=fmax(out1,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out1=clamp(out1,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,slope_ptr));\n"
" out0=select(out0*slope_in,out0,out0 >= 0);\n"
" out1=select(out1*slope_in,out1,out1 >= 0);\n"
"#endif\n"
" const int out_offset=(((out_b_idx+out_c_idx*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
"#ifdef BLOCK_LEAVE\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" if(out_w_idx+1 >= HCOUTW) return;\n"
" vstore4(CONVERT_FLOAT4(out1),1,output+out_offset);\n"
"#else\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0,out1)),0,output+out_offset);\n"
"#endif\n"
"}\n"
"__kernel\n"
"void conv_2d_c4h1w4_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx=out_c_w_idx/HCWB+out_c_base_index;\n"
" if(out_c_idx >= HCOCB) return;\n"
" const int out_w_idx=(out_c_w_idx % HCWB) << 2;\n"
" const int out_b_idx=out_b_h_idx/HCOUTH;//equal to in_b_idx\n"
" const int out_h_idx=out_b_h_idx % HCOUTH;\n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,bias));\n"
" COMPUTE_FLOAT4 out1=out0;\n"
" COMPUTE_FLOAT4 out2=out0;\n"
" COMPUTE_FLOAT4 out3=out0;\n"
" const int in_w0_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_w1_idx_base=in_w0_idx_base+HCSW;\n"
" const int in_w2_idx_base=in_w1_idx_base+HCSW;\n"
" const int in_w3_idx_base=in_w2_idx_base+HCSW;\n"
" const int in_h_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" \n"
" const int kh_start=select(0,(-in_h_idx_base+HCDH-1)/HCDH,in_h_idx_base<0);\n"
" const int in_h_idx_start=mad24(kh_start,HCDH,in_h_idx_base);\n"
" const int in_h_idx_end=min(mad24(HCFH,HCDH,in_h_idx_base),HCINH);\n"
" \n"
" const int weight_oc_offset=HCOCB*HCFH*HCFW*4;\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [1,4*icC4,ocC4*kh*kw,1] xic4\n"
" //index: [0,4*in_c_idx,out_c_idx*kh*kw+kh_start*kw+kw_start,0]\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx) *HCFH+kh_start)*HCFW+0)*4;\n"
" for(int iy=in_h_idx_start; iy<in_h_idx_end; iy += HCDH) {\n"
" const int inp_offset_base=(((out_b_idx+in_c_idx*HCBATCH)*HCINH+iy)*HCINW+0)*4;\n"
" for(int fw=0; fw<HCFW; fw++) {\n"
" const int in_w0_idx=fw*HCDW+in_w0_idx_base;\n"
" const int in_w1_idx=fw*HCDW+in_w1_idx_base;\n"
" const int in_w2_idx=fw*HCDW+in_w2_idx_base;\n"
" const int in_w3_idx=fw*HCDW+in_w3_idx_base;\n"
" COMPUTE_FLOAT4 in0=(in_w0_idx<0 || in_w0_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w0_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in1=(in_w1_idx<0 || in_w1_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w1_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in2=(in_w2_idx<0 || in_w2_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w2_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in3=(in_w3_idx<0 || in_w3_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w3_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset*3));\n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" \n"
" out1=mad(in1.x,weight0,out1);\n"
" out1=mad(in1.y,weight1,out1);\n"
" out1=mad(in1.z,weight2,out1);\n"
" out1=mad(in1.w,weight3,out1);\n"
" \n"
" out2=mad(in2.x,weight0,out2);\n"
" out2=mad(in2.y,weight1,out2);\n"
" out2=mad(in2.z,weight2,out2);\n"
" out2=mad(in2.w,weight3,out2);\n"
" \n"
" out3=mad(in3.x,weight0,out3);\n"
" out3=mad(in3.y,weight1,out3);\n"
" out3=mad(in3.z,weight2,out3);\n"
" out3=mad(in3.w,weight3,out3);\n"
" \n"
" weight_offset += 4;\n"
" }\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
" out1=fmax(out1,(COMPUTE_FLOAT4)0);\n"
" out2=fmax(out2,(COMPUTE_FLOAT4)0);\n"
" out3=fmax(out3,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out1=clamp(out1,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out2=clamp(out2,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out3=clamp(out3,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,slope_ptr));\n"
" out0=select(out0*slope_in,out0,out0 >= 0);\n"
" out1=select(out1*slope_in,out1,out1 >= 0);\n"
" out2=select(out2*slope_in,out2,out2 >= 0);\n"
" out3=select(out3*slope_in,out3,out3 >= 0);\n"
"#endif\n"
" const int out_offset=(((out_b_idx+out_c_idx*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
"#ifdef BLOCK_LEAVE\n"
" const int remain=HCOUTW-out_w_idx;\n"
" if (remain >= 4) {\n"
" vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0,out1,out2,out3)),0,output+out_offset);\n"
" }else if(remain == 3){\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0,out1)),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2,output+out_offset);\n"
" }else if(remain == 2){\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0,out1)),0,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" }\n"
"#else\n"
" vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0,out1,out2,out3)),0,output+out_offset);\n"
"#endif\n"
"}\n"
"__kernel\n"
"void conv_2d_c4h4w1_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx=out_c_w_idx/HCWB+out_c_base_index;\n"
" if(out_c_idx >= HCOCB) return;\n"
" const int out_w_idx=out_c_w_idx % HCWB;\n"
" const int out_b_idx=out_b_h_idx/HCHB;//equal to in_b_idx\n"
" const int out_h_idx=(out_b_h_idx % HCHB) << 2;\n"
" \n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,bias));\n"
" COMPUTE_FLOAT4 out1=out0;\n"
" COMPUTE_FLOAT4 out2=out0;\n"
" COMPUTE_FLOAT4 out3=out0;\n"
" const int in_w_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_h0_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" const int in_h1_idx_base=in_h0_idx_base+HCSH;\n"
" const int in_h2_idx_base=in_h1_idx_base+HCSH;\n"
" const int in_h3_idx_base=in_h2_idx_base+HCSH;\n"
" \n"
" const int kw_start=select(0,(-in_w_idx_base+HCDW-1)/HCDW,in_w_idx_base<0);\n"
" const int in_w_idx_start=mad24(kw_start,HCDW,in_w_idx_base);\n"
" const int in_w_idx_end=min(mad24(HCFW,HCDW,in_w_idx_base),HCINW);\n"
" \n"
" const int weight_oc_offset=HCOCB*HCFH*HCFW*4;\n"
" const int in_hw_size=HCINH*HCINW;\n"
"#ifdef CONV_SPEC_UNROLL\n"
" __attribute__((opencl_unroll_hint))\n"
"#endif\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [1,4*icC4,ocC4*kh*kw,1] xic4\n"
" //index: [0,4*in_c_idx,out_c_idx*kh*kw+kh_start*kw+kw_start,0]\n"
" const int inp_offset_base=(out_b_idx+in_c_idx*HCBATCH)*HCINH*HCINW*4;\n"
" for(int iy=0; iy<HCFH; iy++) {\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx) *HCFH+iy)*HCFW+kw_start)*4;\n"
" const int in_h0_idx=(iy*HCDH+in_h0_idx_base)*HCINW;\n"
" const int in_h1_idx=(iy*HCDH+in_h1_idx_base)*HCINW;\n"
" const int in_h2_idx=(iy*HCDH+in_h2_idx_base)*HCINW;\n"
" const int in_h3_idx=(iy*HCDH+in_h3_idx_base)*HCINW;\n"
" for(int fw=in_w_idx_start; fw<in_w_idx_end; fw += HCDW) {\n"
" COMPUTE_FLOAT4 in0=(in_h0_idx<0 || in_h0_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h0_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in1=(in_h1_idx<0 || in_h1_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h1_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in2=(in_h2_idx<0 || in_h2_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h2_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in3=(in_h3_idx<0 || in_h3_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h3_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset*3));\n"
" \n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" \n"
" out1=mad(in1.x,weight0,out1);\n"
" out1=mad(in1.y,weight1,out1);\n"
" out1=mad(in1.z,weight2,out1);\n"
" out1=mad(in1.w,weight3,out1);\n"
" \n"
" out2=mad(in2.x,weight0,out2);\n"
" out2=mad(in2.y,weight1,out2);\n"
" out2=mad(in2.z,weight2,out2);\n"
" out2=mad(in2.w,weight3,out2);\n"
" \n"
" out3=mad(in3.x,weight0,out3);\n"
" out3=mad(in3.y,weight1,out3);\n"
" out3=mad(in3.z,weight2,out3);\n"
" out3=mad(in3.w,weight3,out3);\n"
" \n"
" weight_offset += 4;\n"
" }\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
" out1=fmax(out1,(COMPUTE_FLOAT4)0);\n"
" out2=fmax(out2,(COMPUTE_FLOAT4)0);\n"
" out3=fmax(out3,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out1=clamp(out1,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out2=clamp(out2,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out3=clamp(out3,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx,slope_ptr));\n"
" out0=select(out0*slope_in,out0,out0 >= 0);\n"
" out1=select(out1*slope_in,out1,out1 >= 0);\n"
" out2=select(out2*slope_in,out2,out2 >= 0);\n"
" out3=select(out3*slope_in,out3,out3 >= 0);\n"
"#endif\n"
" const int out_offset=(((out_b_idx+out_c_idx*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
"#ifdef BLOCK_LEAVE\n"
" const int remain=HCOUTH-out_h_idx;\n"
" if(remain >= 4){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2*HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out3),3*HCOUTW,output+out_offset);\n"
" }else if(remain == 3){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2*HCOUTW,output+out_offset);\n"
" }else if(remain == 2){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" }\n"
"#else\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2*HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out3),3*HCOUTW,output+out_offset);\n"
"#endif\n"
"}\n"
"__kernel\n"
"void conv_2d_c8h4w1_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx_0=((out_c_w_idx/HCWB+out_c_base_index) << 1);\n"
" if(out_c_idx_0 >= HCOCB) return;\n"
" const int out_c_idx_1=out_c_idx_0+1;\n"
" const int out_w_idx=out_c_w_idx % HCWB;\n"
" const int out_b_idx=out_b_h_idx/HCHB;//equal to in_b_idx\n"
" const int out_h_idx=(out_b_h_idx % HCHB) << 2;\n"
" \n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_0,bias));\n"
" COMPUTE_FLOAT4 out1=out0;\n"
" COMPUTE_FLOAT4 out2=out0;\n"
" COMPUTE_FLOAT4 out3=out0;\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" COMPUTE_FLOAT4 out4=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,bias));\n"
" #else\n"
" COMPUTE_FLOAT4 out4=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,bias));\n"
" #endif\n"
" COMPUTE_FLOAT4 out5=out4;\n"
" COMPUTE_FLOAT4 out6=out4;\n"
" COMPUTE_FLOAT4 out7=out4;\n"
" const int in_w_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_h0_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" const int in_h1_idx_base=in_h0_idx_base+HCSH;\n"
" const int in_h2_idx_base=in_h1_idx_base+HCSH;\n"
" const int in_h3_idx_base=in_h2_idx_base+HCSH;\n"
" \n"
" const int kw_start=select(0,(-in_w_idx_base+HCDW-1)/HCDW,in_w_idx_base<0);\n"
" const int in_w_idx_start=mad24(kw_start,HCDW,in_w_idx_base);\n"
" const int in_w_idx_end=min(mad24(HCFW,HCDW,in_w_idx_base),HCINW);\n"
" \n"
" const int weight_oc_offset=HCFH*HCFW*4;\n"
" const int weight_ic_offset=HCOCB*weight_oc_offset;\n"
" const int in_hw_size=HCINH*HCINW;\n"
"#ifdef CONV_SPEC_UNROLL\n"
" __attribute__((opencl_unroll_hint))\n"
"#endif\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [ic/4,ic_4,oc/4,kh*kw,oc_4]\n"
" //index: [0,4*in_c_idx,out_c_idx_0*kh*kw+kh_start*kw+kw_start,0]\n"
" const int inp_offset_base=(out_b_idx+in_c_idx*HCBATCH)*HCINH*HCINW*4;\n"
" for(int iy=0; iy<HCFH; iy++) {\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx_0) *HCFH+iy)*HCFW+kw_start)*4;\n"
" const int in_h0_idx=(iy*HCDH+in_h0_idx_base)*HCINW;\n"
" const int in_h1_idx=(iy*HCDH+in_h1_idx_base)*HCINW;\n"
" const int in_h2_idx=(iy*HCDH+in_h2_idx_base)*HCINW;\n"
" const int in_h3_idx=(iy*HCDH+in_h3_idx_base)*HCINW;\n"
" for(int fw=in_w_idx_start; fw<in_w_idx_end; fw += HCDW) {\n"
" COMPUTE_FLOAT4 in0=(in_h0_idx<0 || in_h0_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h0_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in1=(in_h1_idx<0 || in_h1_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h1_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in2=(in_h2_idx<0 || in_h2_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h2_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in3=(in_h3_idx<0 || in_h3_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h3_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset*3));\n"
" \n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" \n"
" out1=mad(in1.x,weight0,out1);\n"
" out1=mad(in1.y,weight1,out1);\n"
" out1=mad(in1.z,weight2,out1);\n"
" out1=mad(in1.w,weight3,out1);\n"
" \n"
" out2=mad(in2.x,weight0,out2);\n"
" out2=mad(in2.y,weight1,out2);\n"
" out2=mad(in2.z,weight2,out2);\n"
" out2=mad(in2.w,weight3,out2);\n"
" \n"
" out3=mad(in3.x,weight0,out3);\n"
" out3=mad(in3.y,weight1,out3);\n"
" out3=mad(in3.z,weight2,out3);\n"
" out3=mad(in3.w,weight3,out3);\n"
" // weight: [ic/4,ic_4,oc/4,kh*kw,oc_4]\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" weight0=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" weight1=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset));\n"
" weight2=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*2));\n"
" weight3=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*3));\n"
" #else\n"
" weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset));\n"
" weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*2));\n"
" weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*3));\n"
" #endif\n"
" out4=mad(in0.x,weight0,out4);\n"
" out4=mad(in0.y,weight1,out4);\n"
" out4=mad(in0.z,weight2,out4);\n"
" out4=mad(in0.w,weight3,out4);\n"
" \n"
" out5=mad(in1.x,weight0,out5);\n"
" out5=mad(in1.y,weight1,out5);\n"
" out5=mad(in1.z,weight2,out5);\n"
" out5=mad(in1.w,weight3,out5);\n"
" \n"
" out6=mad(in2.x,weight0,out6);\n"
" out6=mad(in2.y,weight1,out6);\n"
" out6=mad(in2.z,weight2,out6);\n"
" out6=mad(in2.w,weight3,out6);\n"
" \n"
" out7=mad(in3.x,weight0,out7);\n"
" out7=mad(in3.y,weight1,out7);\n"
" out7=mad(in3.z,weight2,out7);\n"
" out7=mad(in3.w,weight3,out7);\n"
" \n"
" weight_offset += 4;\n"
" }\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
" out1=fmax(out1,(COMPUTE_FLOAT4)0);\n"
" out2=fmax(out2,(COMPUTE_FLOAT4)0);\n"
" out3=fmax(out3,(COMPUTE_FLOAT4)0);\n"
" out4=fmax(out4,(COMPUTE_FLOAT4)0);\n"
" out5=fmax(out5,(COMPUTE_FLOAT4)0);\n"
" out6=fmax(out6,(COMPUTE_FLOAT4)0);\n"
" out7=fmax(out7,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out1=clamp(out1,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out2=clamp(out2,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out3=clamp(out3,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out4=clamp(out4,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out5=clamp(out5,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out6=clamp(out6,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out7=clamp(out7,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_0,slope_ptr));\n"
" COMPUTE_FLOAT4 slope_in1=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,slope_ptr));\n"
" out0=select(out0*slope_in0,out0,out0 >= 0);\n"
" out1=select(out1*slope_in0,out1,out1 >= 0);\n"
" out2=select(out2*slope_in0,out2,out2 >= 0);\n"
" out3=select(out3*slope_in0,out3,out3 >= 0);\n"
" out4=select(out4*slope_in1,out4,out4 >= 0);\n"
" out5=select(out5*slope_in1,out5,out5 >= 0);\n"
" out6=select(out6*slope_in1,out6,out6 >= 0);\n"
" out7=select(out7*slope_in1,out7,out7 >= 0);\n"
"#endif\n"
" int out_offset=(((out_b_idx+out_c_idx_0*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
"#ifdef BLOCK_LEAVE\n"
" const int remain=HCOUTH-out_h_idx;\n"
" if(remain >= 4){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2*HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out3),3*HCOUTW,output+out_offset);\n"
" }else if(remain == 3){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2*HCOUTW,output+out_offset);\n"
" }else if(remain == 2){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" }\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" if(out_c_idx_1 >= HCOCB){\n"
" return;\n"
" }\n"
" #endif\n"
" out_offset=(((out_b_idx+(out_c_idx_1)*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" if(remain >= 4){\n"
" vstore4(CONVERT_FLOAT4(out4),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out5),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out6),2*HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out7),3*HCOUTW,output+out_offset);\n"
" }else if(remain == 3){\n"
" vstore4(CONVERT_FLOAT4(out4),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out5),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out6),2*HCOUTW,output+out_offset);\n"
" }else if(remain == 2){\n"
" vstore4(CONVERT_FLOAT4(out4),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out5),HCOUTW,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out4),0,output+out_offset);\n"
" }\n"
"#else\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2*HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out3),3*HCOUTW,output+out_offset);\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" if(out_c_idx_1 >= HCOCB){\n"
" return;\n"
" }\n"
" #endif\n"
" out_offset=(((out_b_idx+(out_c_idx_1)*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" vstore4(CONVERT_FLOAT4(out4),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out5),HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out6),2*HCOUTW,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out7),3*HCOUTW,output+out_offset);\n"
"#endif\n"
"}\n"
"__kernel\n"
"void conv_2d_c8h2w1_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx_0=(out_c_w_idx/HCWB+out_c_base_index) << 1;\n"
" if(out_c_idx_0 >= HCOCB) return;\n"
" const int out_c_idx_1=out_c_idx_0+1;\n"
" const int out_w_idx=out_c_w_idx % HCWB;\n"
" const int out_b_idx=out_b_h_idx/HCHB;//equal to in_b_idx\n"
" const int out_h_idx=(out_b_h_idx % HCHB) << 1;\n"
" \n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_0,bias));\n"
" COMPUTE_FLOAT4 out1=out0;\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" COMPUTE_FLOAT4 out2=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,bias));\n"
" #else\n"
" COMPUTE_FLOAT4 out2=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,bias));\n"
" #endif\n"
" COMPUTE_FLOAT4 out3=out2;\n"
" \n"
" const int in_w_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_h0_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" const int in_h1_idx_base=in_h0_idx_base+HCSH;\n"
" \n"
" const int kw_start=select(0,(-in_w_idx_base+HCDW-1)/HCDW,in_w_idx_base<0);\n"
" const int in_w_idx_start=mad24(kw_start,HCDW,in_w_idx_base);\n"
" const int in_w_idx_end=min(mad24(HCFW,HCDW,in_w_idx_base),HCINW);\n"
" \n"
" const int weight_oc_offset=HCFH*HCFW*4;\n"
" const int weight_ic_offset=HCOCB*weight_oc_offset;\n"
" const int in_hw_size=HCINH*HCINW;\n"
" // weight: [ic/4,oc,4],loop: ic/4\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [1,4*icC4,ocC4*kh*kw,1] xic4\n"
" //index: [0,4*in_c_idx,out_c_idx_0*kh*kw+kh_start*kw+kw_start,0]\n"
" const int inp_offset_base=(out_b_idx+in_c_idx*HCBATCH)*HCINH*HCINW*4;\n"
" for(int iy=0; iy<HCFH; iy++) {\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx_0) *HCFH+iy)*HCFW+kw_start)*4;\n"
" const int in_h0_idx=(iy*HCDH+in_h0_idx_base)*HCINW;\n"
" const int in_h1_idx=(iy*HCDH+in_h1_idx_base)*HCINW;\n"
" for(int fw=in_w_idx_start; fw<in_w_idx_end; fw += HCDW) {\n"
" COMPUTE_FLOAT4 in0=(in_h0_idx<0 || in_h0_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h0_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in1=(in_h1_idx<0 || in_h1_idx >= in_hw_size) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_h1_idx+fw,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset*3));\n"
" \n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" \n"
" out1=mad(in1.x,weight0,out1);\n"
" out1=mad(in1.y,weight1,out1);\n"
" out1=mad(in1.z,weight2,out1);\n"
" out1=mad(in1.w,weight3,out1);\n"
" \n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" weight0=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" weight1=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset));\n"
" weight2=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*2));\n"
" weight3=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*3));\n"
" #else\n"
" weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset));\n"
" weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*2));\n"
" weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*3));\n"
" #endif\n"
" out2=mad(in0.x,weight0,out2);\n"
" out2=mad(in0.y,weight1,out2);\n"
" out2=mad(in0.z,weight2,out2);\n"
" out2=mad(in0.w,weight3,out2);\n"
" \n"
" out3=mad(in1.x,weight0,out3);\n"
" out3=mad(in1.y,weight1,out3);\n"
" out3=mad(in1.z,weight2,out3);\n"
" out3=mad(in1.w,weight3,out3);\n"
" \n"
" weight_offset += 4;\n"
" }\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
" out1=fmax(out1,(COMPUTE_FLOAT4)0);\n"
" out2=fmax(out2,(COMPUTE_FLOAT4)0);\n"
" out3=fmax(out3,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out1=clamp(out1,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out2=clamp(out2,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out3=clamp(out3,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_0,slope_ptr));\n"
" COMPUTE_FLOAT4 slope_in1=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,slope_ptr));\n"
" out0=select(out0*slope_in0,out0,out0 >= 0);\n"
" out1=select(out1*slope_in0,out1,out1 >= 0);\n"
" out2=select(out2*slope_in1,out2,out2 >= 0);\n"
" out3=select(out3*slope_in1,out3,out3 >= 0);\n"
"#endif\n"
" int out_offset=(((out_b_idx+out_c_idx_0*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
"#ifdef BLOCK_LEAVE\n"
" const int remain=HCOUTH-out_h_idx;\n"
" if(remain >= 2){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" }\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" if(out_c_idx_1 >= HCOCB){\n"
" return;\n"
" }\n"
" #endif\n"
" out_offset=(((out_b_idx+(out_c_idx_1)*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" if(remain >= 2){\n"
" vstore4(CONVERT_FLOAT4(out2),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out3),HCOUTW,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out2),0,output+out_offset);\n"
" }\n"
"#else\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out1),HCOUTW,output+out_offset);\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" if(out_c_idx_1 >= HCOCB){\n"
" return;\n"
" }\n"
" #endif\n"
" out_offset=(((out_b_idx+(out_c_idx_1)*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" vstore4(CONVERT_FLOAT4(out2),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out3),HCOUTW,output+out_offset);\n"
"#endif\n"
"}\n"
"__kernel\n"
"void conv_2d_c8h1w4_hc(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int2 in_hw,\n"
" __private const int inChannel,\n"
" __private const int in_c_blocks,\n"
" __private const int batch,\n"
" __private const int2 out_hw,\n"
" __private const int2 filter_hw,\n"
" __private const int2 stride_hw,\n"
" __private const int2 pad_hw,\n"
" __private const int2 dilate_hw,\n"
" __private const int out_w_blocks,\n"
" __private const int out_c_blocks,\n"
" __private const int out_h_blocks,\n"
" __private const int out_c_base_index\n"
" #ifdef PRELU\n"
" ,__global const FLOAT *slope_ptr\n"
" #endif\n"
") {\n"
" const int out_c_w_idx=get_global_id(0); //c/4 w\n"
" const int out_b_h_idx=get_global_id(1); //b h\n"
" DEAL_NON_UNIFORM_DIM2(out_c_w_idx,out_b_h_idx);\n"
" const int out_c_idx_0=(out_c_w_idx/HCWB+out_c_base_index) << 1;\n"
" if(out_c_idx_0 >= HCOCB) return;\n"
" const int out_c_idx_1=out_c_idx_0+1;\n"
" const int out_w_idx=(out_c_w_idx % HCWB) << 2;\n"
" const int out_b_idx=out_b_h_idx/HCOUTH;//equal to in_b_idx\n"
" const int out_h_idx=out_b_h_idx % HCOUTH;\n"
" \n"
" COMPUTE_FLOAT4 out0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_0,bias));\n"
" COMPUTE_FLOAT4 out1=out0;\n"
" COMPUTE_FLOAT4 out2=out0;\n"
" COMPUTE_FLOAT4 out3=out0;\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" COMPUTE_FLOAT4 out4=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,bias));\n"
" #else\n"
" COMPUTE_FLOAT4 out4=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,bias));\n"
" #endif\n"
" COMPUTE_FLOAT4 out5=out4;\n"
" COMPUTE_FLOAT4 out6=out4;\n"
" COMPUTE_FLOAT4 out7=out4;\n"
" const int in_w0_idx_base=mad24(out_w_idx,HCSW,-HCPW);\n"
" const int in_w1_idx_base=in_w0_idx_base+HCSW;\n"
" const int in_w2_idx_base=in_w1_idx_base+HCSW;\n"
" const int in_w3_idx_base=in_w2_idx_base+HCSW;\n"
" const int in_h_idx_base=mad24(out_h_idx,HCSH,-HCPH);\n"
" \n"
" const int kh_start=select(0,(-in_h_idx_base+HCDH-1)/HCDH,in_h_idx_base<0);\n"
" const int in_h_idx_start=mad24(kh_start,HCDH,in_h_idx_base);\n"
" const int in_h_idx_end=min(mad24(HCFH,HCDH,in_h_idx_base),HCINH);\n"
" \n"
" const int weight_oc_offset=HCFH*HCFW*4;\n"
" const int weight_ic_offset=HCOCB*weight_oc_offset;\n"
" for(ushort in_c_idx=0; in_c_idx<HCICB; in_c_idx++) {\n"
" //weights NC4HW4 [1,4*icC4,ocC4*kh*kw,1] xic4\n"
" //index: [0,4*in_c_idx,out_c_idx_0*kh*kw+kh_start*kw+kw_start,0]\n"
" int weight_offset=((((4*in_c_idx+0)* HCOCB+out_c_idx_0) *HCFH+kh_start)*HCFW+0)*4;\n"
" for(int iy=in_h_idx_start; iy<in_h_idx_end; iy += HCDH) {\n"
" const int inp_offset_base=(((out_b_idx+in_c_idx*HCBATCH)*HCINH+iy)*HCINW+0)*4;\n"
" for(int fw=0; fw<HCFW; fw++) {\n"
" const int in_w0_idx=fw*HCDW+in_w0_idx_base;\n"
" const int in_w1_idx=fw*HCDW+in_w1_idx_base;\n"
" const int in_w2_idx=fw*HCDW+in_w2_idx_base;\n"
" const int in_w3_idx=fw*HCDW+in_w3_idx_base;\n"
" COMPUTE_FLOAT4 in0=(in_w0_idx<0 || in_w0_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w0_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in1=(in_w1_idx<0 || in_w1_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w1_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in2=(in_w2_idx<0 || in_w2_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w2_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 in3=(in_w3_idx<0 || in_w3_idx >= HCINW) ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(in_w3_idx,input+inp_offset_base));\n"
" COMPUTE_FLOAT4 weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset));\n"
" COMPUTE_FLOAT4 weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset));\n"
" COMPUTE_FLOAT4 weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset*2));\n"
" COMPUTE_FLOAT4 weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_ic_offset*3));\n"
" out0=mad(in0.x,weight0,out0);\n"
" out0=mad(in0.y,weight1,out0);\n"
" out0=mad(in0.z,weight2,out0);\n"
" out0=mad(in0.w,weight3,out0);\n"
" \n"
" out1=mad(in1.x,weight0,out1);\n"
" out1=mad(in1.y,weight1,out1);\n"
" out1=mad(in1.z,weight2,out1);\n"
" out1=mad(in1.w,weight3,out1);\n"
" \n"
" out2=mad(in2.x,weight0,out2);\n"
" out2=mad(in2.y,weight1,out2);\n"
" out2=mad(in2.z,weight2,out2);\n"
" out2=mad(in2.w,weight3,out2);\n"
" \n"
" out3=mad(in3.x,weight0,out3);\n"
" out3=mad(in3.y,weight1,out3);\n"
" out3=mad(in3.z,weight2,out3);\n"
" out3=mad(in3.w,weight3,out3);\n"
" \n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" weight0=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" weight1=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset));\n"
" weight2=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*2));\n"
" weight3=out_c_idx_1 >= HCOCB ? (COMPUTE_FLOAT4)0 : CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*3));\n"
" #else\n"
" weight0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset));\n"
" weight1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset));\n"
" weight2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*2));\n"
" weight3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+weight_offset+weight_oc_offset+weight_ic_offset*3));\n"
" #endif\n"
" out4=mad(in0.x,weight0,out4);\n"
" out4=mad(in0.y,weight1,out4);\n"
" out4=mad(in0.z,weight2,out4);\n"
" out4=mad(in0.w,weight3,out4);\n"
" \n"
" out5=mad(in1.x,weight0,out5);\n"
" out5=mad(in1.y,weight1,out5);\n"
" out5=mad(in1.z,weight2,out5);\n"
" out5=mad(in1.w,weight3,out5);\n"
" \n"
" out6=mad(in2.x,weight0,out6);\n"
" out6=mad(in2.y,weight1,out6);\n"
" out6=mad(in2.z,weight2,out6);\n"
" out6=mad(in2.w,weight3,out6);\n"
" \n"
" out7=mad(in3.x,weight0,out7);\n"
" out7=mad(in3.y,weight1,out7);\n"
" out7=mad(in3.z,weight2,out7);\n"
" out7=mad(in3.w,weight3,out7);\n"
" \n"
" weight_offset += 4;\n"
" }\n"
" }\n"
" }\n"
"#ifdef RELU\n"
" out0=fmax(out0,(COMPUTE_FLOAT4)0);\n"
" out1=fmax(out1,(COMPUTE_FLOAT4)0);\n"
" out2=fmax(out2,(COMPUTE_FLOAT4)0);\n"
" out3=fmax(out3,(COMPUTE_FLOAT4)0);\n"
" out4=fmax(out4,(COMPUTE_FLOAT4)0);\n"
" out5=fmax(out5,(COMPUTE_FLOAT4)0);\n"
" out6=fmax(out6,(COMPUTE_FLOAT4)0);\n"
" out7=fmax(out7,(COMPUTE_FLOAT4)0);\n"
"#endif\n"
"#ifdef RELU6\n"
" out0=clamp(out0,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out1=clamp(out1,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out2=clamp(out2,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out3=clamp(out3,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out4=clamp(out4,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out5=clamp(out5,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out6=clamp(out6,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
" out7=clamp(out7,(COMPUTE_FLOAT4)0,(COMPUTE_FLOAT4)6);\n"
"#endif\n"
"#ifdef PRELU\n"
" COMPUTE_FLOAT4 slope_in0=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_0,slope_ptr));\n"
" COMPUTE_FLOAT4 slope_in1=CONVERT_COMPUTE_FLOAT4(vload4(out_c_idx_1,slope_ptr));\n"
" out0=select(out0*slope_in0,out0,out0 >= 0);\n"
" out1=select(out1*slope_in0,out1,out1 >= 0);\n"
" out2=select(out2*slope_in0,out2,out2 >= 0);\n"
" out3=select(out3*slope_in0,out3,out3 >= 0);\n"
" out4=select(out4*slope_in1,out4,out4 >= 0);\n"
" out5=select(out5*slope_in1,out5,out5 >= 0);\n"
" out6=select(out6*slope_in1,out6,out6 >= 0);\n"
" out7=select(out7*slope_in1,out7,out7 >= 0);\n"
"#endif\n"
" int out_offset=(((out_b_idx+out_c_idx_0*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
"#ifdef BLOCK_LEAVE\n"
" const int remain=HCOUTW-out_w_idx;\n"
" if(remain >= 4){\n"
" vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0,out1,out2,out3)),0,output+out_offset);\n"
" }else if(remain == 3){\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0,out1)),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out2),2,output+out_offset);\n"
" }else if(remain == 2){\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0,out1)),0,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+out_offset);\n"
" }\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" if(out_c_idx_1 >= HCOCB)return;\n"
" #endif\n"
" out_offset=(((out_b_idx+(out_c_idx_1)*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" if(remain >= 4){\n"
" vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out4,out5,out6,out7)),0,output+out_offset);\n"
" }else if(remain == 3){\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out4,out5)),0,output+out_offset);\n"
" vstore4(CONVERT_FLOAT4(out6),2,output+out_offset);\n"
" }else if(remain == 2){\n"
" vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out4,out5)),0,output+out_offset);\n"
" }else if(remain == 1){\n"
" vstore4(CONVERT_FLOAT4(out4),0,output+out_offset);\n"
" }\n"
"#else\n"
" vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0,out1,out2,out3)),0,output+out_offset);\n"
" #ifdef CHANNEL_BOUNDARY_PROTECT\n"
" if(out_c_idx_1 >= HCOCB)return;\n"
" #endif\n"
" out_offset=(((out_b_idx+(out_c_idx_1)*HCBATCH)*HCOUTH+out_h_idx)*HCOUTW+out_w_idx)*4;\n"
" vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out4,out5,out6,out7)),0,output+out_offset);\n"
"#endif\n"
"}\n"
;
#endif
}
