#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* dualrangehist_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// DualRangeHist: single-pass dual masked range-histogram over two float frames\n"
"// A,B (values ~[0,1]) plus an optional per-element base validity mask. Per\n"
"// pixel it computes a SHARED keep bit\n"
"// keep=base & (low <= A <= high) & (low <= B <= high) (raw values,inclusive)\n"
"// and,when kept,increments histA[rint(A*(binNum-1))] and histB[rint(B*(binNum-1))]\n"
"// (round-half-to-even,matching torch.round,done inside the op). Optionally it\n"
"// also accumulates validCount=sum(keep) == sum(histA) == sum(histB).\n"
"//\n"
"// Structure mirrors bincount_buf.cl's register-histogram fast path,extended to\n"
"// two histograms: each work-item keeps two private register histograms\n"
"// (privA/privB[BIN_NUM]) plus a private counter,avoids a data-dependent array\n"
"// index by comparing the rounded bin against every bin unrolled\n"
"// (priv[b] += (bin==b)*keep),and merges across work-items with a fused\n"
"// single-tree log reduction in local memory (run once per histogram,reusing one\n"
"// BIN_NUM*LOCAL_SIZE buffer) plus one global atomic per bin per workgroup. The\n"
"// mask & discretized frames are never materialized.\n"
"#define LOCAL_SIZE 256\n"
"#ifndef BIN_NUM\n"
"#define BIN_NUM 16\n"
"#endif\n"
"// Frames are logically float; read through the precision-dependent FLOAT macro\n"
"// (half in fp16 buffer mode,float in high precision). The bin math is done in\n"
"// float to match the fp32 CPU reference (rint of a small product is exact).\n"
"#define IN_T FLOAT\n"
"#define IN_T4 FLOAT4\n"
"// Optional base mask (third input): int32 or float (fp16 buffer). A component is\n"
"// gated by (m != 0).\n"
"#ifdef HAS_BASE\n"
"#ifdef BASE_FLOAT\n"
"#define BASE_T FLOAT\n"
"#define BASE_T4 FLOAT4\n"
"#else\n"
"#define BASE_T int\n"
"#define BASE_T4 int4\n"
"#endif\n"
"#endif\n"
"// keep bit for one component; bin index via round-half-to-even. `a`,`b` are the\n"
"// raw frame values; `mkeep` folds in the optional base mask (1 when no base).\n"
"#define COMPUTE_KEEP(a, b, mkeep) "" (((float)(a) >= low) & ((float)(a) <= high) & ((float)(b) >= low) & ((float)(b) <= high) & (mkeep))\n"
"#define TO_BIN(v) ((int)rint((float)(v)*scaleF))\n"
"__kernel void dualrangehist_init_buf(\n"
" __global int *histA,\n"
" __global int *histB,\n"
"#ifdef EMIT_VALIDCOUNT\n"
" __global int *validCount,\n"
"#endif\n"
" __private const int binNum) {\n"
" const int idx=get_global_id(0);\n"
" if (idx<binNum) {\n"
" histA[idx]=0;\n"
" } else if (idx<2*binNum) {\n"
" histB[idx-binNum]=0;\n"
" }\n"
"#ifdef EMIT_VALIDCOUNT\n"
" else if (idx == 2*binNum) {\n"
" validCount[0]=0;\n"
" }\n"
"#endif\n"
"}\n"
"// Cross-work-item merge shared by both count kernels. Assumes BIN_NUM*LOCAL_SIZE\n"
"// <= 4096 (guaranteed: the register path is only used for small BIN_NUM). Reduces\n"
"// privA into histA,then reuses the same local buffer for privB into histB,and\n"
"// (optionally) the counter into validCount.\n"
"#define MERGE_HISTOGRAMS() "" __local int reduceBuf[BIN_NUM * LOCAL_SIZE]; "" for (int b = 0; b < BIN_NUM; ++b) { "" reduceBuf[b * LOCAL_SIZE + lid] = privA[b]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int off = LOCAL_SIZE >> 1; off > 0; off >>= 1) { "" if (lid < off) { "" for (int b = 0; b < BIN_NUM; ++b) { "" reduceBuf[b * LOCAL_SIZE + lid] += reduceBuf[b * LOCAL_SIZE + lid + off]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" if (lid == 0) { "" for (int b = 0; b < BIN_NUM; ++b) { "" atomic_add(&histA[b], reduceBuf[b * LOCAL_SIZE]); "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int b = 0; b < BIN_NUM; ++b) { "" reduceBuf[b * LOCAL_SIZE + lid] = privB[b]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int off = LOCAL_SIZE >> 1; off > 0; off >>= 1) { "" if (lid < off) { "" for (int b = 0; b < BIN_NUM; ++b) { "" reduceBuf[b * LOCAL_SIZE + lid] += reduceBuf[b * LOCAL_SIZE + lid + off]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" if (lid == 0) { "" for (int b = 0; b < BIN_NUM; ++b) { "" atomic_add(&histB[b], reduceBuf[b * LOCAL_SIZE]); "" } "" }\n"
"#ifdef EMIT_VALIDCOUNT\n"
"#define MERGE_COUNTER() "" barrier(CLK_LOCAL_MEM_FENCE); "" reduceBuf[lid] = counter; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int off = LOCAL_SIZE >> 1; off > 0; off >>= 1) { "" if (lid < off) { "" reduceBuf[lid] += reduceBuf[lid + off]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" if (lid == 0) { "" atomic_add(&validCount[0], reduceBuf[0]); "" }\n"
"#else\n"
"#define MERGE_COUNTER()\n"
"#endif\n"
"// Contiguous fast path (stride == 1): vectorized 4-wide loads over A,B,base.\n"
"__kernel void dualrangehist_count_buf(\n"
" __global const IN_T *A,\n"
" __global const IN_T *B,\n"
"#ifdef HAS_BASE\n"
" __global const BASE_T *base,\n"
"#endif\n"
" __global int *histA,\n"
" __global int *histB,\n"
"#ifdef EMIT_VALIDCOUNT\n"
" __global int *validCount,\n"
"#endif\n"
" __private const int n,\n"
" __private const float low,\n"
" __private const float high,\n"
" __private const int binNum) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" const float scaleF=(float)(binNum-1);\n"
" int privA[BIN_NUM];\n"
" int privB[BIN_NUM];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" privA[b]=0;\n"
" privB[b]=0;\n"
" }\n"
" int counter=0;\n"
" const int n4=n >> 2;\n"
" for (int i=gid; i<n4; i += gsize) {\n"
" IN_T4 va=vload4(i,A);\n"
" IN_T4 vb=vload4(i,B);\n"
"#ifdef HAS_BASE\n"
" BASE_T4 vm=vload4(i,base);\n"
" int kx=COMPUTE_KEEP(va.x,vb.x,(vm.x != 0));\n"
" int ky=COMPUTE_KEEP(va.y,vb.y,(vm.y != 0));\n"
" int kz=COMPUTE_KEEP(va.z,vb.z,(vm.z != 0));\n"
" int kw=COMPUTE_KEEP(va.w,vb.w,(vm.w != 0));\n"
"#else\n"
" int kx=COMPUTE_KEEP(va.x,vb.x,1);\n"
" int ky=COMPUTE_KEEP(va.y,vb.y,1);\n"
" int kz=COMPUTE_KEEP(va.z,vb.z,1);\n"
" int kw=COMPUTE_KEEP(va.w,vb.w,1);\n"
"#endif\n"
" int ax=TO_BIN(va.x),ay=TO_BIN(va.y),az=TO_BIN(va.z),aw=TO_BIN(va.w);\n"
" int bx=TO_BIN(vb.x),by=TO_BIN(vb.y),bz=TO_BIN(vb.z),bw=TO_BIN(vb.w);\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" privA[b] += (ax == b)*kx+(ay == b)*ky+(az == b)*kz+(aw == b)*kw;\n"
" privB[b] += (bx == b)*kx+(by == b)*ky+(bz == b)*kz+(bw == b)*kw;\n"
" }\n"
" counter += kx+ky+kz+kw;\n"
" }\n"
" // Tail: up to 3 trailing elements when n is not a multiple of 4.\n"
" for (int i=(n4 << 2)+gid; i<n; i += gsize) {\n"
" float a=(float)A[i];\n"
" float b=(float)B[i];\n"
"#ifdef HAS_BASE\n"
" int keep=COMPUTE_KEEP(a,b,(base[i] != 0));\n"
"#else\n"
" int keep=COMPUTE_KEEP(a,b,1);\n"
"#endif\n"
" int ba=TO_BIN(a),bb=TO_BIN(b);\n"
" for (int c=0; c<BIN_NUM; ++c) {\n"
" privA[c] += (ba == c)*keep;\n"
" privB[c] += (bb == c)*keep;\n"
" }\n"
" counter += keep;\n"
" }\n"
" MERGE_HISTOGRAMS();\n"
" MERGE_COUNTER();\n"
"}\n"
"// Downsampled path (stride>1): strided gather over the last two dims,\n"
"// A[..,::s,::s] (and B,base). batch == 1,so nSampled == Hs*Ws.\n"
"__kernel void dualrangehist_sample_buf(\n"
" __global const IN_T *A,\n"
" __global const IN_T *B,\n"
"#ifdef HAS_BASE\n"
" __global const BASE_T *base,\n"
"#endif\n"
" __global int *histA,\n"
" __global int *histB,\n"
"#ifdef EMIT_VALIDCOUNT\n"
" __global int *validCount,\n"
"#endif\n"
" __private const int nSampled,\n"
" __private const int stride,\n"
" __private const int W,\n"
" __private const int Ws,\n"
" __private const float low,\n"
" __private const float high,\n"
" __private const int binNum) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" const float scaleF=(float)(binNum-1);\n"
" int privA[BIN_NUM];\n"
" int privB[BIN_NUM];\n"
" for (int b=0; b<BIN_NUM; ++b) {\n"
" privA[b]=0;\n"
" privB[b]=0;\n"
" }\n"
" int counter=0;\n"
" for (int k=gid; k<nSampled; k += gsize) {\n"
" const int ph=k/Ws;\n"
" const int pw=k-ph*Ws;\n"
" const int flat=(ph*stride)*W+pw*stride;\n"
" float a=(float)A[flat];\n"
" float b=(float)B[flat];\n"
"#ifdef HAS_BASE\n"
" int keep=COMPUTE_KEEP(a,b,(base[flat] != 0));\n"
"#else\n"
" int keep=COMPUTE_KEEP(a,b,1);\n"
"#endif\n"
" int ba=TO_BIN(a),bb=TO_BIN(b);\n"
" for (int c=0; c<BIN_NUM; ++c) {\n"
" privA[c] += (ba == c)*keep;\n"
" privB[c] += (bb == c)*keep;\n"
" }\n"
" counter += keep;\n"
" }\n"
" MERGE_HISTOGRAMS();\n"
" MERGE_COUNTER();\n"
"}\n"
;
#endif
}
