#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* fused_math_s2d_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// FusedMathS2D: per-pixel affine math on two single-plane inputs fused with\n"
"// space-to-depth(block=2). [1,1,H,W] x2 -> [1,13,H/2,W/2],all dense NCHW.\n"
"//\n"
"// P0=alpha*A+beta*B+gamma -> channels 0..3\n"
"// P1=delta*B+epsilon -> channels 4..7\n"
"// P2=P0-P1 -> channels 8..11\n"
"// channel 12=kConst (uniform plane)\n"
"//\n"
"// The op reads 2*H*W elements and writes 13*(H/2)*(W/2)=3.25*H*W,which is the\n"
"// information-theoretic floor,in one dispatch -- there is no algorithmic win\n"
"// available,only bandwidth. Measured on Xclipse 960 (ANGLE-over-Vulkan) the\n"
"// kernel is write-bound: reads run around 74 GB/s,writes around 55 GB/s,and\n"
"// the stores are ~69% of the runtime.\n"
"//\n"
"// Shape of the kernel and why:\n"
"//*dense NCHW everywhere -- NC4HW4 would pad the C=1 inputs to four channels,\n"
"// i.e. 4x the read traffic;\n"
"//*one work-item owns VW whole output pixels,i.e. all 13 channels,so A and B\n"
"// are read exactly once and feed every output;\n"
"//*the 2x2 blocks partition the input,so nothing is shared between\n"
"// work-items: no local memory,no barriers,no subgroup ops (on this stack\n"
"// subgroup shuffles lower to ds_bpermute and lose to plain cached loads);\n"
"//*space-to-depth is a free register swizzle -- in a 2*VW-wide row vector the\n"
"// even lanes are dx=0 and the odd lanes are dx=1,and dy picks the row load;\n"
"//*stores are emitted per (dy,dx) lane group so a single COMPUTE_FLOAT pair is\n"
"// live at a time and P2 reuses P0/P1 out of registers (one subtract).\n"
"// Vector lanes are only ever touched by swizzle: a (FLOAT*)&vec cast would force\n"
"// addressable scratch and spill.\n"
"//\n"
"// Measured and rejected on device (1080x1920,fp16): 2-D grid (371 vs 358 us),\n"
"// forced local sizes 32..512 (372-396),multi-tile channel-major store batching\n"
"// to shorten the live write-stream mix (360-401),typed aligned vector accesses\n"
"// instead of vloadN/vstoreN (neutral),fp16 math instead of fp32 (385).\n"
"#ifndef VW\n"
"#define VW 4 // output pixels per work-item\n"
"#endif\n"
"#ifndef VW2\n"
"#define VW2 8 //=2*VW,input elements per row per work-item\n"
"#endif\n"
"#define PASTE_(a,b) a##b\n"
"#define PASTE(a,b) PASTE_(a,b)\n"
"#define FLOAT_IN PASTE(FLOAT,VW2)\n"
"#define VLOAD_IN PASTE(vload,VW2)\n"
"#if VW == 1\n"
"#define FLOAT_V FLOAT\n"
"#define CFLOAT_V COMPUTE_FLOAT\n"
"#define TO_CFLOAT_V CONVERT_COMPUTE_FLOAT\n"
"#define TO_FLOAT_V CONVERT_FLOAT\n"
"#define VSTORE_V(v,off,ptr) (ptr)[off]=(v)\n"
"#else\n"
"#define FLOAT_V PASTE(FLOAT,VW)\n"
"#define CFLOAT_V PASTE(COMPUTE_FLOAT,VW)\n"
"#define TO_CFLOAT_V PASTE(CONVERT_COMPUTE_FLOAT,VW)\n"
"#define TO_FLOAT_V PASTE(CONVERT_FLOAT,VW)\n"
"#define VSTORE_V PASTE(vstore,VW)\n"
"#endif\n"
"#define STORE_OUT(ch,v) VSTORE_V(TO_FLOAT_V(v),0,output+(ch)*planeStride+o)\n"
"// One (dy,dx) lane group -> its three channels.\n"
"#define GROUP(k, av, bv) "" { "" CFLOAT_V _a = TO_CFLOAT_V(av); "" CFLOAT_V _b = TO_CFLOAT_V(bv); "" CFLOAT_V _p0 = mad(vAlpha, _a, mad(vBeta, _b, vGamma)); "" CFLOAT_V _p1 = mad(vDelta, _b, vEpsilon); "" STORE_OUT(0 + (k), _p0); "" STORE_OUT(4 + (k), _p1); "" STORE_OUT(8 + (k), _p0 - _p1); "" }\n"
"__kernel void fused_math_s2d_buf(\n"
" __global const FLOAT* restrict inputA,\n"
" __global const FLOAT* restrict inputB,\n"
" __global FLOAT* restrict output,\n"
" __private const int inWidth,//=2*outWidth\n"
" __private const int outWidth,\n"
" __private const int outWidthV,//=outWidth/VW\n"
" __private const int total,//=outHeight*outWidthV\n"
" __private const int planeStride,//=outHeight*outWidth\n"
" __private const float alpha,\n"
" __private const float beta,\n"
" __private const float gamma,\n"
" __private const float delta,\n"
" __private const float epsilon,\n"
" __private const float kConst) {\n"
" const int gid=get_global_id(0);\n"
" if (gid >= total) {\n"
" return; // masks only the local-size round-up\n"
" }\n"
" const int ho=gid/outWidthV;\n"
" const int wo=(gid-ho*outWidthV)*VW;\n"
" const int o=ho*outWidth+wo;\n"
" // Uniform channel: depends on no load,so issue it while the four global\n"
" // loads below are still in flight. `restrict` is what lets the compiler keep\n"
" // it there -- without it this store could alias the inputs.\n"
" VSTORE_V((FLOAT_V)((FLOAT)kConst),0,output+12*planeStride+o);\n"
" const int t=(ho*2)*inWidth+wo*2;\n"
" const FLOAT_IN a0=VLOAD_IN(0,inputA+t);\n"
" const FLOAT_IN a1=VLOAD_IN(0,inputA+t+inWidth);\n"
" const FLOAT_IN b0=VLOAD_IN(0,inputB+t);\n"
" const FLOAT_IN b1=VLOAD_IN(0,inputB+t+inWidth);\n"
" const CFLOAT_V vAlpha=(CFLOAT_V)alpha;\n"
" const CFLOAT_V vBeta=(CFLOAT_V)beta;\n"
" const CFLOAT_V vGamma=(CFLOAT_V)gamma;\n"
" const CFLOAT_V vDelta=(CFLOAT_V)delta;\n"
" const CFLOAT_V vEpsilon=(CFLOAT_V)epsilon;\n"
" GROUP(0,a0.even,b0.even) // (dy,dx)=(0,0) -> channels 0,4,8\n"
" GROUP(1,a0.odd,b0.odd) // (0,1) -> channels 1,5,9\n"
" GROUP(2,a1.even,b1.even) // (1,0) -> channels 2,6,10\n"
" GROUP(3,a1.odd,b1.odd) // (1,1) -> channels 3,7,11\n"
"}\n"
;
#endif
}
