#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* mockchain_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// MockChain: a TEMPLATE op demonstrating how one custom OpType dispatches\n"
"// several OpenCL kernels sequentially (a fan-out/fan-in DAG),instead of the\n"
"// usual single kernel. The five kernels below are deliberately trivial\n"
"// elementwise arithmetic -- the value of this file is the dispatch/sync\n"
"// skeleton in MockChainBufExecution.cpp,not the math. To adapt it for a real\n"
"// op,replace each kernel body (and the host-side global/local work sizes and\n"
"// scratch-tensor shapes) with your own; the wiring stays the same.\n"
"//\n"
"// All buffers are read/written through the precision-dependent FLOAT macro,so\n"
"// the same kernels work in fp16 buffer mode (half storage) and high precision\n"
"// (float storage). Every kernel is a plain 1-D elementwise map over `size`\n"
"// elements with a bounds guard,so a single global-work-size=size (rounded up\n"
"// to the local size) drives all of them.\n"
"// func1(x)=x+1\n"
"__kernel void mockchain_func1_buf(\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int size) {\n"
" const int i=get_global_id(0);\n"
" if (i >= size) {\n"
" return;\n"
" }\n"
" output[i]=input[i]+(FLOAT)1;\n"
"}\n"
"// func2(x)=x*2\n"
"__kernel void mockchain_func2_buf(\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int size) {\n"
" const int i=get_global_id(0);\n"
" if (i >= size) {\n"
" return;\n"
" }\n"
" output[i]=input[i]*(FLOAT)2;\n"
"}\n"
"// func3(a,b)=a+b (fan-in of the two branch results)\n"
"__kernel void mockchain_func3_buf(\n"
" __global const FLOAT *inputA,\n"
" __global const FLOAT *inputB,\n"
" __global FLOAT *output,\n"
" __private const int size) {\n"
" const int i=get_global_id(0);\n"
" if (i >= size) {\n"
" return;\n"
" }\n"
" output[i]=inputA[i]+inputB[i];\n"
"}\n"
"// func4(x,k)=x+k (k=per-run offset,passed as a private arg)\n"
"__kernel void mockchain_func4_buf(\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const float offset,\n"
" __private const int size) {\n"
" const int i=get_global_id(0);\n"
" if (i >= size) {\n"
" return;\n"
" }\n"
" output[i]=input[i]+(FLOAT)offset;\n"
"}\n"
"// func5(x)=x*3\n"
"__kernel void mockchain_func5_buf(\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int size) {\n"
" const int i=get_global_id(0);\n"
" if (i >= size) {\n"
" return;\n"
" }\n"
" output[i]=input[i]*(FLOAT)3;\n"
"}\n"
;
#endif
}
