#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* quantile_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// Exact order-statistic selection for up to MAX_TARGETS ranks,computed by\n"
"// binary-searching the monotonic (sign-flipped) uint32 encoding of each\n"
"// float32 element: for float x,key=as_uint(x) XOR (sign ? 0xFFFFFFFF :\n"
"// 0x80000000) is order-preserving over the full float range,so counting how\n"
"// many keys are less-or-equal to a midpoint lets us binary-search directly\n"
"// for the exact bit pattern of the element at a given rank in 32 passes,\n"
"// without ever sorting/gathering the (up to millions-of-elements) array.\n"
"// This avoids TopKV2's k<=1024 buffer-kernel cap entirely.\n"
"#define LOCAL_SIZE 256\n"
"#ifndef MAX_TARGETS\n"
"#define MAX_TARGETS 16\n"
"#endif\n"
"inline uint quantileFloatToKey(float x) {\n"
" uint bits=as_uint(x);\n"
" uint mask=(bits & 0x80000000u) ? 0xFFFFFFFFu : 0x80000000u;\n"
" return bits ^ mask;\n"
"}\n"
"inline float quantileKeyToFloat(uint key) {\n"
" uint bits=(key & 0x80000000u) ? (key ^ 0x80000000u) : (key ^ 0xFFFFFFFFu);\n"
" return as_float(bits);\n"
"}\n"
"// Resets bisection state at the start of every onExecute (loKey/hiKey brackets\n"
"// and countOut are re-initialized per inference call; targetRank/frac are\n"
"// shape-derived constants uploaded once in onResize,not touched here).\n"
"__kernel void quantile_init_buf(\n"
" __global uint *loKey,\n"
" __global uint *hiKey,\n"
" __global uint *countOut,\n"
" __private const int numTargets) {\n"
" const int t=get_global_id(0);\n"
" if (t >= numTargets) {\n"
" return;\n"
" }\n"
" loKey[t]=0u;\n"
" hiKey[t]=0xFFFFFFFFu;\n"
" countOut[t]=0u;\n"
"}\n"
"// One pass of the bisection: for each of `numTargets` independent target\n"
"// ranks,count how many input elements have key <= mid(target),where\n"
"// mid(target) is derived from the target's current [loKey,hiKey] bracket.\n"
"// countOut must be zero before this dispatch (quantile_update_buf resets it\n"
"// at the end of the previous iteration; the host clears it before pass 0).\n"
"__kernel void quantile_count_buf(\n"
" __global const FLOAT *input,\n"
" __global const uint *loKey,\n"
" __global const uint *hiKey,\n"
" __global uint *countOut,\n"
" __private const int n,\n"
" __private const int numTargets) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" __local uint reduceBuf[LOCAL_SIZE];\n"
" uint mid[MAX_TARGETS];\n"
" for (int t=0; t<numTargets; ++t) {\n"
" uint lo=loKey[t];\n"
" uint hi=hiKey[t];\n"
" mid[t]=lo+((hi-lo) >> 1);\n"
" }\n"
" uint priv[MAX_TARGETS];\n"
" for (int t=0; t<numTargets; ++t) {\n"
" priv[t]=0;\n"
" }\n"
" for (int i=gid; i<n; i += gsize) {\n"
" uint key=quantileFloatToKey((float)input[i]);\n"
" for (int t=0; t<numTargets; ++t) {\n"
" priv[t] += (key <= mid[t]) ? 1u : 0u;\n"
" }\n"
" }\n"
" for (int t=0; t<numTargets; ++t) {\n"
" reduceBuf[lid]=priv[t];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int off=LOCAL_SIZE >> 1; off>0; off >>= 1) {\n"
" if (lid<off) {\n"
" reduceBuf[lid] += reduceBuf[lid+off];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" atomic_add(&countOut[t],reduceBuf[0]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
"}\n"
"// Narrows each target's [loKey,hiKey] bracket by one bit using the count\n"
"// produced by quantile_count_buf,and resets countOut for the next pass.\n"
"__kernel void quantile_update_buf(\n"
" __global uint *loKey,\n"
" __global uint *hiKey,\n"
" __global uint *countOut,\n"
" __global const int *targetRank,\n"
" __private const int numTargets) {\n"
" const int t=get_global_id(0);\n"
" if (t >= numTargets) {\n"
" return;\n"
" }\n"
" uint lo=loKey[t];\n"
" uint hi=hiKey[t];\n"
" if (lo<hi) {\n"
" uint mid=lo+((hi-lo) >> 1);\n"
" uint cnt=countOut[t];\n"
" if ((int)cnt >= targetRank[t]+1) {\n"
" hi=mid;\n"
" } else {\n"
" lo=mid+1;\n"
" }\n"
" loKey[t]=lo;\n"
" hiKey[t]=hi;\n"
" }\n"
" countOut[t]=0;\n"
"}\n"
"// After convergence loKey[2*i] and loKey[2*i+1] hold the exact keys of the\n"
"// floor/ceil order statistics for quantile level i; blend them with the\n"
"// (compile-time-known) interpolation weight.\n"
"__kernel void quantile_finalize_buf(\n"
" __global const uint *loKey,\n"
" __global const float *frac,\n"
" __global FLOAT *output,\n"
" __private const int numQ) {\n"
" const int i=get_global_id(0);\n"
" if (i >= numQ) {\n"
" return;\n"
" }\n"
" float lower=quantileKeyToFloat(loKey[2*i]);\n"
" float upper=quantileKeyToFloat(loKey[2*i+1]);\n"
" output[i]=(FLOAT)(lower+frac[i]*(upper-lower));\n"
"}\n"
;
#endif
}
