#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* quantile_u8_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// Opt-in fast path (QuantileParam.assumeUint8Source): the caller asserts\n"
"// every input element is already exactly round(level)/255 for some uint8\n"
"// level in [0,255] (e.g. a uint8 image plane normalized to [0,1]). Under\n"
"// that assumption there are only 256 possible distinct values total,so a\n"
"// single EXACT shared histogram (not per-target,same sharing idea as\n"
"// quantile_hist_buf.cl) resolves every quantile level directly -- no\n"
"// bisection/refinement pass needed at all,unlike the general-input path.\n"
"// Must not be used for inputs outside [0,1] or not uint8-sourced: values\n"
"// get clamped/rounded to the nearest of the 256 levels,which is silently\n"
"// wrong for anything else.\n"
"#define U8_BUCKETS 256\n"
"inline int quantileU8Level(float x) {\n"
" int level=(int)(x*255.0f+0.5f);\n"
" level=max(0,min(255,level));\n"
" return level;\n"
"}\n"
"__kernel void quantile_u8_hist_init_buf(__global uint *hist) {\n"
" const int i=get_global_id(0);\n"
" if (i<U8_BUCKETS) {\n"
" hist[i]=0u;\n"
" }\n"
"}\n"
"__kernel void quantile_u8_hist_build_buf(\n"
" __global const FLOAT *input,\n"
" __global uint *hist,\n"
" __private const int n) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" const int lsize=get_local_size(0);\n"
" __local uint localHist[U8_BUCKETS];\n"
" for (int i=lid; i<U8_BUCKETS; i += lsize) {\n"
" localHist[i]=0u;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=gid; i<n; i += gsize) {\n"
" atomic_inc(&localHist[quantileU8Level((float)input[i])]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=lid; i<U8_BUCKETS; i += lsize) {\n"
" if (localHist[i] != 0u) {\n"
" atomic_add(&hist[i],localHist[i]);\n"
" }\n"
" }\n"
"}\n"
"// One work-item per quantile level: scans the shared 256-bucket histogram\n"
"// once,finding both the floor- and ceil-rank buckets in the same pass,and\n"
"// writes the interpolated result directly -- no separate refinement stage.\n"
"__kernel void quantile_u8_finalize_buf(\n"
" __global const uint *hist,\n"
" __global const int *loRank,\n"
" __global const int *hiRank,\n"
" __global const float *frac,\n"
" __global FLOAT *output,\n"
" __private const int numQ) {\n"
" const int i=get_global_id(0);\n"
" if (i >= numQ) {\n"
" return;\n"
" }\n"
" const int loR=loRank[i];\n"
" const int hiR=hiRank[i];\n"
" uint cum=0u;\n"
" int loLevel=U8_BUCKETS-1;\n"
" int hiLevel=U8_BUCKETS-1;\n"
" bool loFound=false;\n"
" for (int b=0; b<U8_BUCKETS; ++b) {\n"
" uint next=cum+hist[b];\n"
" if (!loFound && (int)next >= loR+1) {\n"
" loLevel=b;\n"
" loFound=true;\n"
" }\n"
" if ((int)next >= hiR+1) {\n"
" hiLevel=b;\n"
" break;\n"
" }\n"
" cum=next;\n"
" }\n"
" float lower=loLevel/255.0f;\n"
" float upper=hiLevel/255.0f;\n"
" output[i]=(FLOAT)(lower+frac[i]*(upper-lower));\n"
"}\n"
;
#endif
}
