#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* quantile_hist_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// Experimental: single shared histogram (built once,not once per target,\n"
"// unlike the earlier failed radix-select attempt) over the top HIST_BITS\n"
"// bits of the same monotonic key used by quantile_buf.cl's exact bisection.\n"
"// Bucketing by the monotonic key (not the raw linear value) preserves the\n"
"// same log-uniform relative-precision behavior the bisection has -- a plain\n"
"// linear-value histogram would badly lose relative precision for values\n"
"// near 0. One pass resolves HIST_BITS bits for every target at once; the\n"
"// remaining bits are then finished by a few passes of the existing exact\n"
"// bisection kernels (quantile_count_buf/quantile_update_buf),reusing\n"
"// already-verified code for the refinement tail instead of duplicating it.\n"
"#ifndef HIST_BITS\n"
"#define HIST_BITS 12\n"
"#endif\n"
"#define HIST_BUCKETS (1 << HIST_BITS)\n"
"inline uint quantileHistFloatToKey(float x) {\n"
" uint bits=as_uint(x);\n"
" uint mask=(bits & 0x80000000u) ? 0xFFFFFFFFu : 0x80000000u;\n"
" return bits ^ mask;\n"
"}\n"
"inline uint quantileHistBucket(uint key) {\n"
" return key >> (32-HIST_BITS);\n"
"}\n"
"__kernel void quantile_hist_init_buf(__global uint *hist) {\n"
" const int i=get_global_id(0);\n"
" if (i<HIST_BUCKETS) {\n"
" hist[i]=0u;\n"
" }\n"
"}\n"
"__kernel void quantile_hist_build_buf(\n"
" __global const FLOAT *input,\n"
" __global uint *hist,\n"
" __private const int n) {\n"
" const int gid=get_global_id(0);\n"
" const int gsize=get_global_size(0);\n"
" const int lid=get_local_id(0);\n"
" const int lsize=get_local_size(0);\n"
" __local uint localHist[HIST_BUCKETS];\n"
" for (int i=lid; i<HIST_BUCKETS; i += lsize) {\n"
" localHist[i]=0u;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=gid; i<n; i += gsize) {\n"
" uint key=quantileHistFloatToKey((float)input[i]);\n"
" atomic_inc(&localHist[quantileHistBucket(key)]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=lid; i<HIST_BUCKETS; i += lsize) {\n"
" if (localHist[i] != 0u) {\n"
" atomic_add(&hist[i],localHist[i]);\n"
" }\n"
" }\n"
"}\n"
"// One work-item per target scans the (small,shared) histogram to find the\n"
"// bucket containing its target rank,and seeds loKey/hiKey to that bucket's\n"
"// key range for the existing bisection kernels to refine further.\n"
"__kernel void quantile_hist_scan_buf(\n"
" __global const uint *hist,\n"
" __global uint *loKey,\n"
" __global uint *hiKey,\n"
" __global uint *countOut,\n"
" __global const int *targetRank,\n"
" __private const int numTargets) {\n"
" const int t=get_global_id(0);\n"
" if (t >= numTargets) {\n"
" return;\n"
" }\n"
" int rank=targetRank[t];\n"
" uint cum=0u;\n"
" int chosen=HIST_BUCKETS-1;\n"
" for (int b=0; b<HIST_BUCKETS; ++b) {\n"
" uint c=hist[b];\n"
" if ((int)(cum+c) >= rank+1) {\n"
" chosen=b;\n"
" break;\n"
" }\n"
" cum += c;\n"
" }\n"
" uint lo=((uint)chosen) << (32-HIST_BITS);\n"
" uint hi=(chosen == HIST_BUCKETS-1) ? 0xFFFFFFFFu : ((((uint)chosen+1) << (32-HIST_BITS))-1u);\n"
" loKey[t]=lo;\n"
" hiKey[t]=hi;\n"
" countOut[t]=0u;\n"
"}\n"
;
#endif
}
